// Package policyengine provides a Caddy HTTP middleware handler that evaluates
// allow/block/honeypot policy rules with correct matching semantics. It replaces
// Coraza SecRule generation for these rule types, fixing the @pm substring
// matching issue (e.g., @pm /admin matching /administrator).
//
// Rules are loaded from a JSON file generated by wafctl and hot-reloaded via
// mtime polling. The plugin sets Caddy variables for allow rules so downstream
// handlers (like coraza_waf) can be conditionally skipped.
//
// Module ID: http.handlers.policy_engine
package policyengine

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/caddyconfig/caddyfile"
	"github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	"go.uber.org/zap"
)

// defaultBodyMaxSize matches the Coraza WAF request_body_limit (13 MiB).
const defaultBodyMaxSize = 13 * 1024 * 1024

// maxRegexLen is the maximum allowed regex pattern length (bytes).
// Go's RE2 engine is linear-time, but extremely large compiled regexes
// can still consume significant memory. 8 KiB is generous for any
// reasonable security rule pattern.
const maxRegexLen = 8 * 1024

func init() {
	caddy.RegisterModule(PolicyEngine{})
	httpcaddyfile.RegisterHandlerDirective("policy_engine", parseCaddyfilePolicyEngine)
}

// ─── Types ──────────────────────────────────────────────────────────

// PolicyEngine evaluates allow/block/honeypot/rate_limit rules before the WAF.
type PolicyEngine struct {
	// RulesFile is the path to the JSON policy rules file generated by wafctl.
	RulesFile string `json:"rules_file,omitempty"`

	// Rules are inline policy rules (alternative to RulesFile for testing).
	Rules []PolicyRule `json:"rules,omitempty"`

	// ReloadInterval is how often to check RulesFile for changes. Default 5s.
	ReloadInterval caddy.Duration `json:"reload_interval,omitempty"`

	// BodyMaxSize is the maximum bytes to buffer for body field matching.
	// Default 13 MiB (matching Coraza WAF request_body_limit).
	BodyMaxSize int64 `json:"body_max_size,omitempty"`

	// HideHeaders suppresses debug response headers (X-Blocked-By,
	// X-Blocked-Rule, X-Policy-Tags, X-RateLimit-Monitor) in responses.
	// Caddy variables are still set regardless. Use this in production
	// to avoid exposing internal rule names to clients.
	HideHeaders bool `json:"hide_headers,omitempty"`

	// compiled state (not serialized)
	rules          []compiledRule
	logger         *zap.Logger
	mu             *sync.RWMutex
	lastMod        time.Time
	stopPoll       chan struct{}
	rlState        *rateLimitState
	rlGlobalConfig *parsedRLGlobalConfig
	stopSweep      chan struct{}
}

// PolicyRulesFile is the top-level JSON structure of the rules file.
type PolicyRulesFile struct {
	Rules           []PolicyRule           `json:"rules"`
	RateLimitConfig *RateLimitGlobalConfig `json:"rate_limit_config,omitempty"`
	Generated       string                 `json:"generated"`
	Version         int                    `json:"version"`
}

// PolicyRule is a single policy rule.
type PolicyRule struct {
	ID         string            `json:"id"`
	Name       string            `json:"name"`
	Type       string            `json:"type"`              // "allow", "block", "honeypot", "rate_limit"
	Service    string            `json:"service,omitempty"` // hostname or "*" (rate_limit rules only)
	Conditions []PolicyCondition `json:"conditions"`
	GroupOp    string            `json:"group_op"` // "and" or "or"
	RateLimit  *RateLimitConfig  `json:"rate_limit,omitempty"`
	Tags       []string          `json:"tags,omitempty"`
	Enabled    bool              `json:"enabled"`
	Priority   int               `json:"priority"`
}

// PolicyCondition is a single match condition.
type PolicyCondition struct {
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    string `json:"value"`
	// Phase 2: managed list support
	ListItems []string `json:"list_items,omitempty"`
	ListKind  string   `json:"list_kind,omitempty"`
}

// ─── Compiled State ─────────────────────────────────────────────────

type compiledRule struct {
	rule       PolicyRule
	conditions []compiledCondition
	needsBody  bool              // true if any condition or RL key uses body/body_json/body_form
	rlConfig   *compiledRLConfig // non-nil for rate_limit rules
}

type compiledCondition struct {
	field     string
	operator  string
	name      string // for named fields (header, cookie, args, body_json, body_form, etc.)
	exactVal  string
	prefix    string
	suffix    string
	contains  string
	regex     *regexp.Regexp
	ipNets    []net.IPNet       // CIDR ranges for ip_match/not_ip_match and in_list(ip kind with CIDRs)
	ipSet     map[[16]byte]bool // O(1) lookup for single IPs in large ip-kind lists
	stringSet map[string]bool
	negate    bool
	isExists  bool // true for "exists" operator (field presence check)
}

// bodyFields lists condition fields that require reading the request body.
var bodyFields = map[string]bool{
	"body":      true,
	"body_json": true,
	"body_form": true,
}

// parsedBody caches pre-parsed representations of the request body to avoid
// re-parsing JSON or form data on every condition evaluation.
type parsedBody struct {
	raw      []byte
	jsonRoot interface{} // lazily parsed on first body_json access
	jsonOK   bool        // true if jsonRoot was successfully parsed
	jsonDone bool        // true if JSON parsing was attempted
	formVals url.Values  // lazily parsed on first body_form access
	formDone bool        // true if form parsing was attempted
}

// getJSON returns the pre-parsed JSON root, parsing lazily on first call.
func (pb *parsedBody) getJSON() (interface{}, bool) {
	if pb == nil || len(pb.raw) == 0 {
		return nil, false
	}
	if !pb.jsonDone {
		pb.jsonDone = true
		var root interface{}
		if err := json.Unmarshal(pb.raw, &root); err == nil {
			pb.jsonRoot = root
			pb.jsonOK = true
		}
	}
	return pb.jsonRoot, pb.jsonOK
}

// getForm returns the pre-parsed form values, parsing lazily on first call.
func (pb *parsedBody) getForm() url.Values {
	if pb == nil || len(pb.raw) == 0 {
		return nil
	}
	if !pb.formDone {
		pb.formDone = true
		vals, err := url.ParseQuery(string(pb.raw))
		if err == nil {
			pb.formVals = vals
		}
	}
	return pb.formVals
}

// ─── Caddy Module Interface ─────────────────────────────────────────

func (PolicyEngine) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.policy_engine",
		New: func() caddy.Module { return new(PolicyEngine) },
	}
}

func (pe *PolicyEngine) Provision(ctx caddy.Context) error {
	pe.logger = ctx.Logger()
	pe.mu = &sync.RWMutex{}
	pe.rlState = newRateLimitState()

	if pe.ReloadInterval == 0 {
		pe.ReloadInterval = caddy.Duration(5 * time.Second)
	}
	if pe.BodyMaxSize == 0 {
		pe.BodyMaxSize = defaultBodyMaxSize
	}

	// Load rules from file or inline config.
	if pe.RulesFile != "" {
		if err := pe.loadFromFile(); err != nil {
			// Not fatal — file may not exist yet. Start with empty rules.
			pe.logger.Warn("failed to load rules file, starting empty",
				zap.String("file", pe.RulesFile), zap.Error(err))
			pe.rules = nil
		}
		// Start hot-reload polling.
		pe.stopPoll = make(chan struct{})
		go pe.pollForChanges()
	} else if len(pe.Rules) > 0 {
		compiled, err := compileRules(pe.Rules)
		if err != nil {
			return fmt.Errorf("compiling inline rules: %w", err)
		}
		pe.rules = compiled
		pe.rlState.updateZones(compiled)
	}

	// Start sweep goroutine for expired rate limit counters.
	pe.startSweep()

	ruleCount := len(pe.rules)
	enabledCount := 0
	rlCount := 0
	for _, r := range pe.rules {
		if r.rule.Enabled {
			enabledCount++
		}
		if r.rule.Type == "rate_limit" {
			rlCount++
		}
	}
	pe.logger.Info("policy engine provisioned",
		zap.Int("rules", ruleCount),
		zap.Int("enabled", enabledCount),
		zap.Int("rate_limit_zones", rlCount),
		zap.String("rules_file", pe.RulesFile))

	return nil
}

func (pe *PolicyEngine) Validate() error {
	if pe.RulesFile == "" && len(pe.Rules) == 0 {
		return fmt.Errorf("either rules_file or inline rules must be configured")
	}
	return nil
}

func (pe *PolicyEngine) Cleanup() error {
	if pe.stopPoll != nil {
		close(pe.stopPoll)
	}
	if pe.stopSweep != nil {
		close(pe.stopSweep)
	}
	// Note: pe.rlState is intentionally NOT nilled here. ServeHTTP reads
	// pe.rlState without holding mu (it's set once in Provision and never
	// changed), so nilling it here would introduce a data race with
	// in-flight requests. The GC will collect it after the handler is
	// dereferenced by Caddy.
	return nil
}

// ─── ServeHTTP ──────────────────────────────────────────────────────

func (pe *PolicyEngine) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyhttp.Handler) error {
	pe.mu.RLock()
	rules := pe.rules
	globalCfg := pe.rlGlobalConfig
	pe.mu.RUnlock()

	var pb *parsedBody
	var bodyRead bool

	for _, cr := range rules {
		if !cr.rule.Enabled {
			continue
		}

		// Rate limit rules require service matching before condition evaluation.
		if cr.rule.Type == "rate_limit" && !matchService(cr.rule.Service, r) {
			continue
		}

		// Lazy body read: only when a rule needs body fields and we haven't read yet.
		if cr.needsBody && !bodyRead {
			if r.Body != nil && r.Body != http.NoBody {
				buf, err := readBody(r, pe.BodyMaxSize)
				if err != nil {
					pe.logger.Debug("failed to read request body", zap.Error(err))
				}
				pb = &parsedBody{raw: buf}
			} else {
				pb = &parsedBody{}
			}
			bodyRead = true
		}

		if !matchRule(cr, r, pb) {
			continue
		}

		// Rule matched — take action.
		switch cr.rule.Type {
		case "allow":
			caddyhttp.SetVar(r.Context(), "policy_engine.action", "allow")
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
			if len(cr.rule.Tags) > 0 {
				caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
			}
			pe.logger.Info("policy allow",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.Strings("tags", cr.rule.Tags),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return next.ServeHTTP(w, r)

		case "block", "honeypot":
			// Set Caddy variables so log_append captures them reliably
			// (response headers may be lowercased by HTTP/2 and lost through handle_errors).
			caddyhttp.SetVar(r.Context(), "policy_engine.action", cr.rule.Type)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
			if len(cr.rule.Tags) > 0 {
				caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
			}
			// Also set response headers for downstream visibility (error pages, debugging).
			// Suppressed when HideHeaders is true to avoid exposing rule internals.
			if !pe.HideHeaders {
				w.Header().Set("X-Blocked-By", "policy-engine")
				w.Header().Set("X-Blocked-Rule", cr.rule.Name)
				if len(cr.rule.Tags) > 0 {
					w.Header().Set("X-Policy-Tags", strings.Join(cr.rule.Tags, ","))
				}
			}
			pe.logger.Info("policy block",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.String("type", cr.rule.Type),
				zap.Strings("tags", cr.rule.Tags),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return caddyhttp.Error(http.StatusForbidden, nil)

		case "rate_limit":
			if cr.rlConfig == nil || pe.rlState == nil {
				continue
			}

			z := pe.rlState.getZone(cr.rule.ID)
			if z == nil {
				continue
			}

			// Resolve the rate limit key from the request.
			key := resolveRateLimitKey(cr.rlConfig.Key, r, pb)
			if key == "" {
				// Empty key (e.g., missing header) — skip this rule.
				continue
			}

			allowed, count, limit := z.allow(key, time.Now())
			remaining := limit - int(count)

			if cr.rlConfig.Action == "log_only" {
				// Monitor mode: set headers but don't block.
				if !pe.HideHeaders {
					setRateLimitHeaders(w, limit, remaining, cr.rlConfig.parsedWindow, cr.rule.Name)
					w.Header().Set("X-RateLimit-Monitor", cr.rule.Name)
				}
				caddyhttp.SetVar(r.Context(), "policy_engine.action", "rate_limit_monitor")
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
				// Don't return — continue to next rule (monitoring doesn't short-circuit).
				continue
			}

			if !allowed {
				// Rate exceeded — return 429.
				caddyhttp.SetVar(r.Context(), "policy_engine.action", "rate_limit")
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
				if len(cr.rule.Tags) > 0 {
					caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
				}
				// Numeric rate limit headers (Limit, Remaining, Reset) and
				// Retry-After are functional — clients need them for backoff.
				// Only suppress the rule name in X-RateLimit-Policy when
				// HideHeaders is true.
				rlHeaderName := cr.rule.Name
				if pe.HideHeaders {
					rlHeaderName = ""
				}
				setRateLimitHeaders(w, limit, 0, cr.rlConfig.parsedWindow, rlHeaderName)

				jitter := float64(0)
				if globalCfg != nil {
					jitter = globalCfg.jitter
				}
				w.Header().Set("Retry-After", retryAfterSeconds(cr.rlConfig.parsedWindow, jitter))

				pe.logger.Info("rate limited",
					zap.String("rule_id", cr.rule.ID),
					zap.String("rule_name", cr.rule.Name),
					zap.String("key", key),
					zap.Int64("count", count),
					zap.Int("limit", limit),
					zap.Strings("tags", cr.rule.Tags),
					zap.String("client_ip", clientIP(r)),
					zap.String("uri", r.RequestURI))
				return caddyhttp.Error(http.StatusTooManyRequests, nil)
			}

			// Under limit — set informational headers and continue.
			if !pe.HideHeaders {
				setRateLimitHeaders(w, limit, remaining, cr.rlConfig.parsedWindow, cr.rule.Name)
			}
		}
	}

	// No rule matched — pass through.
	return next.ServeHTTP(w, r)
}

// ─── Body Reading ───────────────────────────────────────────────────

// readBody reads up to maxSize bytes from r.Body and re-wraps the body
// so downstream handlers still see the full content.
// Pattern borrowed from github.com/erfianugrah/caddy-body-matcher.
func readBody(r *http.Request, maxSize int64) ([]byte, error) {
	lr := io.LimitReader(r.Body, maxSize+1)
	buf, err := io.ReadAll(lr)
	if err != nil {
		// Re-wrap partial data + remaining original body.
		r.Body = io.NopCloser(io.MultiReader(bytes.NewReader(buf), r.Body))
		return nil, err
	}

	if int64(len(buf)) > maxSize {
		// Body exceeds limit — re-assemble full body for downstream,
		// but only use first maxSize bytes for matching.
		r.Body = io.NopCloser(io.MultiReader(bytes.NewReader(buf), r.Body))
		buf = buf[:maxSize]
	} else {
		// Body fully consumed — replace with buffered copy.
		r.Body = io.NopCloser(bytes.NewReader(buf))
	}

	return buf, nil
}

// ─── Rule Matching ──────────────────────────────────────────────────

func matchRule(cr compiledRule, r *http.Request, pb *parsedBody) bool {
	if len(cr.conditions) == 0 {
		// No conditions = matches all requests.
		return true
	}

	if cr.rule.GroupOp == "or" {
		for _, cc := range cr.conditions {
			if matchCondition(cc, r, pb) {
				return true
			}
		}
		return false
	}

	// Default: AND — all conditions must match.
	for _, cc := range cr.conditions {
		if !matchCondition(cc, r, pb) {
			return false
		}
	}
	return true
}

func matchCondition(cc compiledCondition, r *http.Request, pb *parsedBody) bool {
	// Special handling for "exists" operator on body_json — checks field presence,
	// not string comparison.
	if cc.isExists {
		result := extractFieldExists(cc, pb)
		if cc.negate {
			return !result
		}
		return result
	}

	target := extractField(cc, r, pb)
	result := evalOperator(cc, target)
	if cc.negate {
		return !result
	}
	return result
}

// extractField gets the request value for a condition's field.
//
// Field semantics:
//   - "path":     full request URI including query string (r.URL.RequestURI())
//   - "uri_path": path component only, without query string (r.URL.Path)
//
// These are intentionally distinct — "path" matches the full URI for backward
// compatibility with wafctl-generated rules that need query string matching.
func extractField(cc compiledCondition, r *http.Request, pb *parsedBody) string {
	switch cc.field {
	case "ip":
		return clientIP(r)
	case "path":
		// NOTE: "path" includes the query string (full request URI).
		// Use "uri_path" for path-only matching without query string.
		return r.URL.RequestURI()
	case "uri_path":
		return r.URL.Path
	case "host":
		return r.Host
	case "method":
		return r.Method
	case "user_agent":
		return r.Header.Get("User-Agent")
	case "query":
		return r.URL.RawQuery
	case "country":
		return r.Header.Get("Cf-Ipcountry")
	case "referer":
		return r.Header.Get("Referer")
	case "http_version":
		return r.Proto
	case "header":
		if cc.name != "" {
			return r.Header.Get(cc.name)
		}
		return ""
	case "cookie":
		if cc.name != "" {
			if c, err := r.Cookie(cc.name); err == nil {
				return c.Value
			}
		}
		return ""
	case "args":
		if cc.name != "" {
			return r.URL.Query().Get(cc.name)
		}
		return ""
	case "body":
		if pb != nil {
			return string(pb.raw)
		}
		return ""
	case "body_json":
		if pb == nil {
			return ""
		}
		if cc.name != "" && len(pb.raw) > 0 {
			root, ok := pb.getJSON()
			if !ok {
				return ""
			}
			val, found := resolveJSONPathParsed(root, cc.name)
			if !found {
				return ""
			}
			return jsonValueToString(val)
		}
		return string(pb.raw)
	case "body_form":
		if pb == nil {
			return ""
		}
		if cc.name != "" && len(pb.raw) > 0 {
			values := pb.getForm()
			if values == nil {
				return ""
			}
			if fv, ok := values[cc.name]; ok && len(fv) > 0 {
				return fv[0]
			}
		}
		return ""
	default:
		return ""
	}
}

// extractFieldExists checks whether a body_json field exists (for the "exists" operator).
func extractFieldExists(cc compiledCondition, pb *parsedBody) bool {
	if cc.field != "body_json" || cc.name == "" || pb == nil || len(pb.raw) == 0 {
		return false
	}
	root, ok := pb.getJSON()
	if !ok {
		return false
	}
	_, found := resolveJSONPathParsed(root, cc.name)
	return found
}

// evalOperator evaluates the operator against the extracted target value.
// The negate flag is handled by the caller (matchCondition).
func evalOperator(cc compiledCondition, target string) bool {
	switch cc.operator {
	case "eq":
		return target == cc.exactVal
	case "neq":
		// neq returns the *equality* result here; the negate flag on the
		// compiledCondition (set during compilation for neq/not_ip_match/
		// not_in_list) causes matchCondition to invert this result.
		// This two-step pattern keeps evalOperator focused on positive
		// matching while matchCondition handles all negation uniformly.
		return target == cc.exactVal
	case "contains":
		return strings.Contains(target, cc.contains)
	case "begins_with":
		return strings.HasPrefix(target, cc.prefix)
	case "ends_with":
		return strings.HasSuffix(target, cc.suffix)
	case "regex":
		if cc.regex != nil {
			return cc.regex.MatchString(target)
		}
		return false
	case "ip_match", "not_ip_match":
		return evalIPMatch(cc, target)
	case "in", "in_list":
		// in_list with ip kind uses IP-aware matching.
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			return evalIPMatch(cc, target)
		}
		return cc.stringSet[target]
	case "not_in_list":
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			return evalIPMatch(cc, target)
		}
		return cc.stringSet[target]
	default:
		return false
	}
}

// evalIPMatch checks if target IP is in the compiled IP set or CIDR ranges.
// Uses O(1) hash set for single IPs (ipSet), falls back to linear scan for CIDRs.
func evalIPMatch(cc compiledCondition, target string) bool {
	ip := net.ParseIP(target)
	if ip == nil {
		return false
	}
	// O(1) hash lookup for single IPs.
	if cc.ipSet != nil {
		var key [16]byte
		copy(key[:], ip.To16())
		if cc.ipSet[key] {
			return true
		}
	}
	// Linear scan for CIDR ranges (typically small count even in large lists).
	for _, n := range cc.ipNets {
		if n.Contains(ip) {
			return true
		}
	}
	return false
}

// ipTo16Key normalizes an IP to a 16-byte array key for hash set storage.
func ipTo16Key(ip net.IP) [16]byte {
	var key [16]byte
	copy(key[:], ip.To16())
	return key
}

// compileIPList compiles a list of IP/CIDR strings into an ipSet (for single IPs)
// and ipNets (for CIDR ranges). Single IPs go into the O(1) hash set;
// CIDRs that aren't /32 or /128 go into the linear-scan slice.
func compileIPList(items []string) (map[[16]byte]bool, []net.IPNet, error) {
	ipSet := make(map[[16]byte]bool, len(items))
	var nets []net.IPNet

	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		if strings.Contains(item, "/") {
			_, ipNet, err := net.ParseCIDR(item)
			if err != nil {
				return nil, nil, fmt.Errorf("parsing CIDR %q: %w", item, err)
			}
			// Check if this is a single-host CIDR (/32 or /128).
			ones, bits := ipNet.Mask.Size()
			if ones == bits {
				// Single host — put in hash set.
				ipSet[ipTo16Key(ipNet.IP)] = true
			} else {
				nets = append(nets, *ipNet)
			}
		} else {
			ip := net.ParseIP(item)
			if ip == nil {
				return nil, nil, fmt.Errorf("parsing IP %q: invalid address", item)
			}
			ipSet[ipTo16Key(ip)] = true
		}
	}

	return ipSet, nets, nil
}

// ─── JSON Helpers ───────────────────────────────────────────────────

// resolveJSONPath walks a dot-path like ".user.roles.0" through parsed JSON.
// Leading dot is optional. Returns (value, found).
// This variant parses from raw bytes — use resolveJSONPathParsed when
// you have a pre-parsed root (to avoid re-parsing per condition).
func resolveJSONPath(body []byte, dotPath string) (interface{}, bool) {
	var root interface{}
	if err := json.Unmarshal(body, &root); err != nil {
		return nil, false
	}
	return resolveJSONPathParsed(root, dotPath)
}

// resolveJSONPathParsed walks a dot-path through an already-parsed JSON value.
// Leading dot is optional. Returns (value, found).
func resolveJSONPathParsed(root interface{}, dotPath string) (interface{}, bool) {
	dotPath = strings.TrimPrefix(dotPath, ".")
	if dotPath == "" {
		return root, true
	}

	parts := strings.Split(dotPath, ".")
	current := root

	for _, part := range parts {
		switch v := current.(type) {
		case map[string]interface{}:
			val, ok := v[part]
			if !ok {
				return nil, false
			}
			current = val
		case []interface{}:
			idx, err := strconv.Atoi(part)
			if err != nil || idx < 0 || idx >= len(v) {
				return nil, false
			}
			current = v[idx]
		default:
			return nil, false
		}
	}

	return current, true
}

// jsonValueToString converts a JSON value to its string representation.
func jsonValueToString(v interface{}) string {
	switch val := v.(type) {
	case string:
		return val
	case float64:
		if val == float64(int64(val)) {
			return strconv.FormatInt(int64(val), 10)
		}
		return strconv.FormatFloat(val, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(val)
	case nil:
		return "null"
	default:
		b, err := json.Marshal(val)
		if err != nil {
			return fmt.Sprintf("%v", val)
		}
		return string(b)
	}
}

// ─── Client IP ──────────────────────────────────────────────────────

// clientIP extracts the client IP from the request, stripping the port.
func clientIP(r *http.Request) string {
	// Caddy sets r.RemoteAddr to the real client IP (after trusted_proxies resolution).
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}

// ─── Rule Compilation ───────────────────────────────────────────────

func compileRules(rules []PolicyRule) ([]compiledRule, error) {
	var compiled []compiledRule
	for _, rule := range rules {
		cr, err := compileRule(rule)
		if err != nil {
			return nil, fmt.Errorf("rule %q (%s): %w", rule.Name, rule.ID, err)
		}
		compiled = append(compiled, cr)
	}

	// Sort by priority (lower first), then by ID for determinism.
	sort.Slice(compiled, func(i, j int) bool {
		if compiled[i].rule.Priority != compiled[j].rule.Priority {
			return compiled[i].rule.Priority < compiled[j].rule.Priority
		}
		return compiled[i].rule.ID < compiled[j].rule.ID
	})

	return compiled, nil
}

// validRuleTypes is the set of recognized rule types.
var validRuleTypes = map[string]bool{
	"allow":      true,
	"block":      true,
	"honeypot":   true,
	"rate_limit": true,
}

func compileRule(rule PolicyRule) (compiledRule, error) {
	cr := compiledRule{rule: rule}

	// Validate rule type early — unknown types would silently match
	// conditions but take no action in ServeHTTP.
	if !validRuleTypes[rule.Type] {
		return cr, fmt.Errorf("unsupported rule type %q (must be allow, block, honeypot, or rate_limit)", rule.Type)
	}

	for _, cond := range rule.Conditions {
		cc, err := compileCondition(cond)
		if err != nil {
			return cr, fmt.Errorf("condition %s %s: %w", cond.Field, cond.Operator, err)
		}
		cr.conditions = append(cr.conditions, cc)
		if bodyFields[cond.Field] {
			cr.needsBody = true
		}
	}

	// Compile rate limit config if this is a rate_limit rule.
	if rule.Type == "rate_limit" {
		rlCfg, err := compileRLConfig(rule.RateLimit)
		if err != nil {
			return cr, fmt.Errorf("rate_limit config: %w", err)
		}
		cr.rlConfig = rlCfg
		if rlCfg.needsBody {
			cr.needsBody = true
		}
	}

	return cr, nil
}

func compileCondition(cond PolicyCondition) (compiledCondition, error) {
	cc := compiledCondition{
		field:    cond.Field,
		operator: cond.Operator,
	}

	// Parse named fields: "Name:value" format.
	value := cond.Value
	switch cond.Field {
	case "header", "cookie", "args", "body_form":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	case "body_json":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	}

	// Handle negate operators.
	switch cond.Operator {
	case "neq", "not_ip_match", "not_in_list":
		cc.negate = true
	}

	// Compile based on operator.
	switch cond.Operator {
	case "eq", "neq":
		cc.exactVal = value

	case "contains":
		cc.contains = value

	case "begins_with":
		cc.prefix = value

	case "ends_with":
		cc.suffix = value

	case "regex":
		if len(value) > maxRegexLen {
			return cc, fmt.Errorf("regex pattern too long (%d bytes, max %d)", len(value), maxRegexLen)
		}
		re, err := regexp.Compile(value)
		if err != nil {
			return cc, fmt.Errorf("invalid regex %q: %w", value, err)
		}
		cc.regex = re

	case "ip_match", "not_ip_match":
		nets, err := parseIPNets(value)
		if err != nil {
			return cc, fmt.Errorf("invalid IP/CIDR %q: %w", value, err)
		}
		cc.ipNets = nets

	case "in":
		// Accept both pipe-separated ("a|b|c") and space-separated ("a b c") values.
		// The wafctl frontend stores "in" values with pipes (PipeTagInput convention),
		// while some seeded rules use spaces. Normalize pipes to spaces, then split.
		cc.stringSet = make(map[string]bool)
		normalized := strings.ReplaceAll(value, "|", " ")
		for _, item := range strings.Fields(normalized) {
			cc.stringSet[item] = true
		}

	case "in_list", "not_in_list":
		// Managed list operators — items are pre-resolved by wafctl into ListItems.
		// ListKind determines how to compile: "ip" → ipSet + ipNets, everything else → stringSet.
		if cond.ListKind == "ip" {
			ipSet, nets, err := compileIPList(cond.ListItems)
			if err != nil {
				return cc, fmt.Errorf("compiling IP list: %w", err)
			}
			cc.ipSet = ipSet
			cc.ipNets = nets
		} else {
			cc.stringSet = make(map[string]bool, len(cond.ListItems))
			for _, item := range cond.ListItems {
				if item != "" {
					cc.stringSet[item] = true
				}
			}
		}

	case "exists":
		// "exists" checks for field presence (body_json dot-path).
		// No value comparison needed.
		cc.isExists = true

	default:
		return cc, fmt.Errorf("unsupported operator %q", cond.Operator)
	}

	return cc, nil
}

// parseIPNets parses a comma-or-space-separated list of IPs and CIDRs.
func parseIPNets(value string) ([]net.IPNet, error) {
	// Normalize: replace commas with spaces, then split.
	normalized := strings.ReplaceAll(value, ",", " ")
	tokens := strings.Fields(normalized)

	var nets []net.IPNet
	for _, tok := range tokens {
		if strings.Contains(tok, "/") {
			_, ipNet, err := net.ParseCIDR(tok)
			if err != nil {
				return nil, fmt.Errorf("parsing CIDR %q: %w", tok, err)
			}
			nets = append(nets, *ipNet)
		} else {
			ip := net.ParseIP(tok)
			if ip == nil {
				return nil, fmt.Errorf("parsing IP %q: invalid address", tok)
			}
			// Single IP → /32 or /128 mask.
			mask := net.CIDRMask(32, 32)
			if ip.To4() == nil {
				mask = net.CIDRMask(128, 128)
			}
			nets = append(nets, net.IPNet{IP: ip, Mask: mask})
		}
	}

	return nets, nil
}

// ─── Hot Reload ─────────────────────────────────────────────────────

func (pe *PolicyEngine) pollForChanges() {
	ticker := time.NewTicker(time.Duration(pe.ReloadInterval))
	defer ticker.Stop()

	for {
		select {
		case <-pe.stopPoll:
			return
		case <-ticker.C:
			pe.checkReload()
		}
	}
}

func (pe *PolicyEngine) checkReload() {
	info, err := os.Stat(pe.RulesFile)
	if err != nil {
		if os.IsNotExist(err) {
			// File removed — clear rules and rate limit zones.
			pe.mu.Lock()
			if len(pe.rules) > 0 {
				pe.logger.Warn("rules file removed, clearing rules",
					zap.String("file", pe.RulesFile))
				pe.rules = nil
				pe.rlGlobalConfig = nil
				pe.lastMod = time.Time{}
			}
			pe.mu.Unlock()
			if pe.rlState != nil {
				pe.rlState.updateZones(nil)
			}
		}
		return
	}

	if !info.ModTime().After(pe.lastMod) {
		return
	}

	if err := pe.loadFromFile(); err != nil {
		pe.logger.Error("hot reload failed, keeping old rules",
			zap.String("file", pe.RulesFile), zap.Error(err))
	}
}

func (pe *PolicyEngine) loadFromFile() error {
	// Open and stat the same file descriptor to avoid TOCTOU races
	// (the file could be modified between a separate ReadFile and Stat).
	f, err := os.Open(pe.RulesFile)
	if err != nil {
		return fmt.Errorf("opening rules file: %w", err)
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return fmt.Errorf("stat rules file: %w", err)
	}

	data, err := io.ReadAll(f)
	if err != nil {
		return fmt.Errorf("reading rules file: %w", err)
	}

	var file PolicyRulesFile
	if err := json.Unmarshal(data, &file); err != nil {
		return fmt.Errorf("parsing rules file: %w", err)
	}

	compiled, err := compileRules(file.Rules)
	if err != nil {
		return fmt.Errorf("compiling rules: %w", err)
	}

	// Parse global rate limit config.
	globalCfg := compileRLGlobalConfig(file.RateLimitConfig)

	// Check if sweep interval changed (need to restart sweep goroutine).
	oldSweepInterval := pe.sweepInterval()

	pe.mu.Lock()
	pe.rules = compiled
	pe.rlGlobalConfig = globalCfg
	pe.lastMod = info.ModTime()
	pe.mu.Unlock()

	// Update rate limit zones — preserves counters for unchanged rules.
	if pe.rlState != nil {
		pe.rlState.updateZones(compiled)
	}

	// Restart sweep goroutine if the sweep interval changed.
	newSweepInterval := pe.sweepInterval()
	if newSweepInterval != oldSweepInterval {
		pe.logger.Info("sweep interval changed, restarting sweep goroutine",
			zap.Duration("old", oldSweepInterval),
			zap.Duration("new", newSweepInterval))
		pe.restartSweep()
	}

	enabledCount := 0
	rlCount := 0
	for _, r := range compiled {
		if r.rule.Enabled {
			enabledCount++
		}
		if r.rule.Type == "rate_limit" {
			rlCount++
		}
	}
	pe.logger.Info("rules loaded",
		zap.Int("total", len(compiled)),
		zap.Int("enabled", enabledCount),
		zap.Int("rate_limit_zones", rlCount),
		zap.String("generated", file.Generated))

	return nil
}

// ─── Caddyfile Parsing ──────────────────────────────────────────────

func (pe *PolicyEngine) UnmarshalCaddyfile(d *caddyfile.Dispenser) error {
	d.Next() // consume directive name

	for d.NextBlock(0) {
		switch d.Val() {
		case "rules_file":
			if !d.NextArg() {
				return d.ArgErr()
			}
			pe.RulesFile = d.Val()

		case "reload_interval":
			if !d.NextArg() {
				return d.ArgErr()
			}
			dur, err := caddy.ParseDuration(d.Val())
			if err != nil {
				return d.Errf("invalid reload_interval: %v", err)
			}
			pe.ReloadInterval = caddy.Duration(dur)

		case "body_max_size":
			if !d.NextArg() {
				return d.ArgErr()
			}
			size, err := parseSize(d.Val())
			if err != nil {
				return d.Errf("invalid body_max_size: %v", err)
			}
			pe.BodyMaxSize = size

		case "hide_headers":
			pe.HideHeaders = true

		case "rule":
			rule, err := parseInlineRule(d)
			if err != nil {
				return err
			}
			pe.Rules = append(pe.Rules, rule)

		default:
			return d.Errf("unrecognized option: %s", d.Val())
		}
	}

	return nil
}

func parseInlineRule(d *caddyfile.Dispenser) (PolicyRule, error) {
	var rule PolicyRule
	rule.Enabled = true // inline rules default to enabled
	rule.GroupOp = "and"

	for nesting := d.Nesting(); d.NextBlock(nesting); {
		switch d.Val() {
		case "id":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.ID = d.Val()
		case "name":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Name = d.Val()
		case "type":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Type = d.Val()
		case "group_op":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.GroupOp = d.Val()
		case "priority":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			var p int
			if _, err := fmt.Sscanf(d.Val(), "%d", &p); err != nil {
				return rule, d.Errf("invalid priority: %v", err)
			}
			rule.Priority = p
		case "condition":
			args := d.RemainingArgs()
			if len(args) < 3 {
				return rule, d.Errf("condition requires: field operator value")
			}
			rule.Conditions = append(rule.Conditions, PolicyCondition{
				Field:    args[0],
				Operator: args[1],
				Value:    strings.Join(args[2:], " "),
			})
		default:
			return rule, d.Errf("unrecognized rule option: %s", d.Val())
		}
	}

	return rule, nil
}

// parseSize parses a human-readable size string like "13mb", "1024kb", "5gb".
// Supports kb, mb, gb suffixes (case-insensitive). Plain numbers are bytes.
func parseSize(s string) (int64, error) {
	s = strings.TrimSpace(strings.ToLower(s))
	multiplier := int64(1)
	switch {
	case strings.HasSuffix(s, "gb"):
		multiplier = 1024 * 1024 * 1024
		s = strings.TrimSuffix(s, "gb")
	case strings.HasSuffix(s, "mb"):
		multiplier = 1024 * 1024
		s = strings.TrimSuffix(s, "mb")
	case strings.HasSuffix(s, "kb"):
		multiplier = 1024
		s = strings.TrimSuffix(s, "kb")
	}
	n, err := strconv.ParseInt(strings.TrimSpace(s), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid size %q: %w", s, err)
	}
	return n * multiplier, nil
}

func parseCaddyfilePolicyEngine(h httpcaddyfile.Helper) (caddyhttp.MiddlewareHandler, error) {
	pe := new(PolicyEngine)
	err := pe.UnmarshalCaddyfile(h.Dispenser)
	return pe, err
}

// ─── Interface Assertions ───────────────────────────────────────────

var (
	_ caddy.Module                = (*PolicyEngine)(nil)
	_ caddy.Provisioner           = (*PolicyEngine)(nil)
	_ caddy.Validator             = (*PolicyEngine)(nil)
	_ caddy.CleanerUpper          = (*PolicyEngine)(nil)
	_ caddyhttp.MiddlewareHandler = (*PolicyEngine)(nil)
	_ caddyfile.Unmarshaler       = (*PolicyEngine)(nil)
)
