// Package policyengine provides a Caddy HTTP middleware handler that evaluates
// allow/block/honeypot policy rules with correct matching semantics. It replaces
// Coraza SecRule generation for these rule types, fixing the @pm substring
// matching issue (e.g., @pm /admin matching /administrator).
//
// Rules are loaded from a JSON file generated by wafctl and hot-reloaded via
// mtime polling. The plugin sets Caddy variables for allow rules so downstream
// handlers (like coraza_waf) can be conditionally skipped.
//
// Module ID: http.handlers.policy_engine
package policyengine

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/caddyconfig/caddyfile"
	"github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	libinjection "github.com/corazawaf/libinjection-go"
	"go.uber.org/zap"
)

// defaultBodyMaxSize matches the Coraza WAF request_body_limit (13 MiB).
const defaultBodyMaxSize = 13 * 1024 * 1024

// maxRegexLen is the maximum allowed regex pattern length (bytes).
// Go's RE2 engine is linear-time, so large patterns are safe from ReDoS.
// CRS 4.x rules (especially RCE/PHP injection) can have patterns up to
// ~12 KiB due to extensive command/function name alternations.
// 128 KiB provides ample headroom for current and future CRS versions.
const maxRegexLen = 128 * 1024

func init() {
	caddy.RegisterModule(PolicyEngine{})
	httpcaddyfile.RegisterHandlerDirective("policy_engine", parseCaddyfilePolicyEngine)
}

// ─── Types ──────────────────────────────────────────────────────────

// PolicyEngine evaluates allow/block/honeypot/rate_limit rules before the WAF.
type PolicyEngine struct {
	// RulesFile is the path to the JSON policy rules file generated by wafctl.
	RulesFile string `json:"rules_file,omitempty"`

	// DefaultRulesFile is the path to the JSON file containing built-in default
	// rules (e.g., CRS-equivalent detect rules). These are merged with user rules
	// at load time. User rules override defaults by ID, and disabled defaults
	// are filtered out via the DisabledDefaultRules list in the user rules file.
	DefaultRulesFile string `json:"default_rules_file,omitempty"`

	// Rules are inline policy rules (alternative to RulesFile for testing).
	Rules []PolicyRule `json:"rules,omitempty"`

	// DefaultRules are inline default rules (alternative to DefaultRulesFile for testing).
	DefaultRules []PolicyRule `json:"default_rules,omitempty"`

	// ReloadInterval is how often to check RulesFile for changes. Default 5s.
	ReloadInterval caddy.Duration `json:"reload_interval,omitempty"`

	// BodyMaxSize is the maximum bytes to buffer for body field matching.
	// Default 13 MiB (matching Coraza WAF request_body_limit).
	BodyMaxSize int64 `json:"body_max_size,omitempty"`

	// HideHeaders suppresses debug response headers (X-Blocked-By,
	// X-Blocked-Rule, X-Policy-Tags, X-RateLimit-Monitor) in responses.
	// Caddy variables are still set regardless. Use this in production
	// to avoid exposing internal rule names to clients.
	HideHeaders bool `json:"hide_headers,omitempty"`

	// compiled state (not serialized)
	rules          []compiledRule
	logger         *zap.Logger
	mu             *sync.RWMutex
	lastMod        time.Time
	lastDefaultMod time.Time // mtime of default rules file
	stopPoll       chan struct{}
	rlState        *rateLimitState
	rlGlobalConfig *parsedRLGlobalConfig
	respHeaders    *compiledResponseHeaders // CSP + security headers
	wafConfig      *compiledWafConfig       // anomaly scoring thresholds
	stopSweep      chan struct{}
}

// PolicyRulesFile is the top-level JSON structure of the user rules file.
type PolicyRulesFile struct {
	Rules                []PolicyRule           `json:"rules"`
	DisabledDefaultRules []string               `json:"disabled_default_rules,omitempty"`
	RateLimitConfig      *RateLimitGlobalConfig `json:"rate_limit_config,omitempty"`
	ResponseHeaders      *ResponseHeaderConfig  `json:"response_headers,omitempty"`
	WafConfig            *WafConfig             `json:"waf_config,omitempty"`
	Generated            string                 `json:"generated"`
	Version              int                    `json:"version"`
}

// DefaultRulesFile is the top-level JSON structure of the default rules file.
// Default rules ship with the Docker image and provide built-in detection
// (CRS-equivalent rules, protocol enforcement, etc.). They are merged with
// user rules at load time; user rules override defaults by ID.
// Supports both legacy "rules" key and CRS converter "default_rules" key.
type DefaultRulesFile struct {
	Rules        []PolicyRule `json:"rules"`
	DefaultRules []PolicyRule `json:"default_rules"` // CRS converter output format
	Version      int          `json:"version"`
	CRSVersion   string       `json:"crs_version,omitempty"`
}

// WafConfig controls the anomaly scoring engine's behavior.
type WafConfig struct {
	ParanoiaLevel     int                         `json:"paranoia_level"`
	InboundThreshold  int                         `json:"inbound_threshold"`
	OutboundThreshold int                         `json:"outbound_threshold"`
	PerService        map[string]WafServiceConfig `json:"per_service,omitempty"`
}

// WafServiceConfig allows per-service threshold and PL overrides.
type WafServiceConfig struct {
	ParanoiaLevel     int `json:"paranoia_level,omitempty"`
	InboundThreshold  int `json:"inbound_threshold,omitempty"`
	OutboundThreshold int `json:"outbound_threshold,omitempty"`
}

// compiledWafConfig is the pre-compiled WAF config for O(1) per-request lookup.
type compiledWafConfig struct {
	defaultPL           int
	defaultInThreshold  int
	defaultOutThreshold int
	services            map[string]compiledWafServiceConfig
}

type compiledWafServiceConfig struct {
	paranoiaLevel    int
	inboundThreshold int
}

// scoreAccumulator tracks per-request anomaly scores during detect rule evaluation.
type scoreAccumulator struct {
	inbound int
	matched []matchedRule
}

// matchedRule records a detect rule that fired for audit logging.
type matchedRule struct {
	ruleID   string
	ruleName string
	severity string
	score    int
	matches  []matchDetail // per-condition match details (nil for non-detect)
}

// matchDetail records what a single condition matched — field, variable name,
// the actual value tested, and what the operator matched against.
// Mirrors Coraza's MATCHED_VAR_NAME / MATCHED_VAR / TX:0 / logdata.
type matchDetail struct {
	Field       string `json:"field"`                  // condition field (e.g., "all_args_values", "header")
	VarName     string `json:"var_name"`               // SecRule-style variable name (e.g., "ARGS:username", "REQUEST_HEADERS:User-Agent")
	Value       string `json:"value"`                  // actual input value that was tested (truncated)
	MatchedData string `json:"matched_data,omitempty"` // regex group 0, phrase_match hit, or matched literal
	Operator    string `json:"operator"`               // operator name (e.g., "regex", "phrase_match")
}

// keyedValue pairs a variable name/key with its value for multi-field extraction.
type keyedValue struct {
	key string // e.g., "username", "User-Agent", "session_id"
	val string
}

// PolicyRule is a single policy rule.
type PolicyRule struct {
	ID         string            `json:"id"`
	Name       string            `json:"name"`
	Type       string            `json:"type"`              // "allow", "block", "honeypot", "rate_limit", "detect"
	Service    string            `json:"service,omitempty"` // hostname or "*" (rate_limit and detect rules)
	Conditions []PolicyCondition `json:"conditions"`
	GroupOp    string            `json:"group_op"` // "and" or "or"
	RateLimit  *RateLimitConfig  `json:"rate_limit,omitempty"`
	Tags       []string          `json:"tags,omitempty"`
	Enabled    bool              `json:"enabled"`
	Priority   int               `json:"priority"`

	// Detect rule fields (anomaly scoring)
	Severity      string `json:"severity,omitempty"`       // CRITICAL(5), ERROR(4), WARNING(3), NOTICE(2)
	ParanoiaLevel int    `json:"paranoia_level,omitempty"` // 1-4; rule only evaluates if configured PL >= this
}

// PolicyCondition is a single match condition.
type PolicyCondition struct {
	Field      string   `json:"field"`
	Operator   string   `json:"operator"`
	Value      string   `json:"value"`
	Transforms []string `json:"transforms,omitempty"` // ordered transform chain applied before operator
	Negate     bool     `json:"negate,omitempty"`     // CRS !@ prefix — inverts operator result
	// Phase 2: managed list support
	ListItems []string `json:"list_items,omitempty"`
	ListKind  string   `json:"list_kind,omitempty"`
}

// ─── Compiled State ─────────────────────────────────────────────────

type compiledRule struct {
	rule       PolicyRule
	conditions []compiledCondition
	needsBody  bool              // true if any condition or RL key uses body/body_json/body_form
	rlConfig   *compiledRLConfig // non-nil for rate_limit rules
	score      int               // severity-derived score for detect rules (0 for non-detect)
}

type compiledCondition struct {
	field        string
	operator     string
	name         string // for named fields (header, cookie, args, body_json, body_form, etc.)
	exactVal     string
	prefix       string
	suffix       string
	contains     string
	regex        *regexp.Regexp
	ipNets       []net.IPNet       // CIDR ranges for ip_match/not_ip_match and in_list(ip kind with CIDRs)
	ipSet        map[[16]byte]bool // O(1) lookup for single IPs in large ip-kind lists
	stringSet    map[string]bool
	negate       bool
	isExists     bool            // true for "exists" operator (field presence check)
	transforms   []transformFunc // ordered transform chain applied before operator evaluation
	acMatcher    *ACMatcher      // compiled Aho-Corasick automaton for phrase_match
	isMulti      bool            // true for aggregate fields (all_args, all_headers, etc.)
	isCount      bool            // true for count: pseudo-field
	countField   string          // the underlying field for count: (e.g., "all_args")
	numericVal   float64         // pre-parsed numeric value for gt/ge/lt/le operators
	byteRangeSet *[256]bool      // allowed byte values for validate_byte_range
}

// bodyFields lists condition fields that require reading the request body.
var bodyFields = map[string]bool{
	"body":      true,
	"body_json": true,
	"body_form": true,
}

// needsBodyField returns true if a field requires reading the request body.
// This covers direct body fields AND aggregate fields that include POST params.
func needsBodyField(field string) bool {
	switch field {
	case "all_args", "all_args_values", "all_args_names":
		return true // these include POST form params from the body
	}
	if strings.HasPrefix(field, countPrefix) {
		underlying := field[len(countPrefix):]
		switch underlying {
		case "all_args", "all_args_values", "all_args_names":
			return true
		}
	}
	return false
}

// multiFields lists aggregate fields that iterate over multiple values.
// When a condition uses one of these, matchCondition iterates all values
// and returns true if ANY value matches (OR semantics).
var multiFields = map[string]bool{
	"all_args":          true,
	"all_args_values":   true,
	"all_args_names":    true,
	"all_headers":       true,
	"all_headers_names": true,
	"all_cookies":       true,
	"all_cookies_names": true,
}

// countPrefix is the prefix for count pseudo-fields (e.g., "count:all_args").
const countPrefix = "count:"

// parsedBody caches pre-parsed representations of the request body to avoid
// re-parsing JSON or form data on every condition evaluation.
type parsedBody struct {
	raw      []byte
	jsonRoot interface{} // lazily parsed on first body_json access
	jsonOK   bool        // true if jsonRoot was successfully parsed
	jsonDone bool        // true if JSON parsing was attempted
	formVals url.Values  // lazily parsed on first body_form access
	formDone bool        // true if form parsing was attempted
}

// getJSON returns the pre-parsed JSON root, parsing lazily on first call.
func (pb *parsedBody) getJSON() (interface{}, bool) {
	if pb == nil || len(pb.raw) == 0 {
		return nil, false
	}
	if !pb.jsonDone {
		pb.jsonDone = true
		var root interface{}
		if err := json.Unmarshal(pb.raw, &root); err == nil {
			pb.jsonRoot = root
			pb.jsonOK = true
		}
	}
	return pb.jsonRoot, pb.jsonOK
}

// getForm returns the pre-parsed form values, parsing lazily on first call.
func (pb *parsedBody) getForm() url.Values {
	if pb == nil || len(pb.raw) == 0 {
		return nil
	}
	if !pb.formDone {
		pb.formDone = true
		vals, err := url.ParseQuery(string(pb.raw))
		if err == nil {
			pb.formVals = vals
		}
	}
	return pb.formVals
}

// ─── Caddy Module Interface ─────────────────────────────────────────

func (PolicyEngine) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.policy_engine",
		New: func() caddy.Module { return new(PolicyEngine) },
	}
}

func (pe *PolicyEngine) Provision(ctx caddy.Context) error {
	pe.logger = ctx.Logger()
	pe.mu = &sync.RWMutex{}
	pe.rlState = newRateLimitState()

	if pe.ReloadInterval == 0 {
		pe.ReloadInterval = caddy.Duration(5 * time.Second)
	}
	if pe.BodyMaxSize == 0 {
		pe.BodyMaxSize = defaultBodyMaxSize
	}

	// Load rules from file or inline config.
	if pe.RulesFile != "" {
		if err := pe.loadFromFile(); err != nil {
			// Not fatal — file may not exist yet. Start with empty rules.
			pe.logger.Warn("failed to load rules file, starting empty",
				zap.String("file", pe.RulesFile), zap.Error(err))
			pe.rules = nil
		}
		// Start hot-reload polling.
		pe.stopPoll = make(chan struct{})
		go pe.pollForChanges()
	} else if len(pe.Rules) > 0 || len(pe.DefaultRules) > 0 {
		merged := mergeDefaultAndUserRules(pe.DefaultRules, pe.Rules, nil)
		compiled, err := compileRules(merged)
		if err != nil {
			return fmt.Errorf("compiling inline rules: %w", err)
		}
		pe.rules = compiled
		pe.rlState.updateZones(compiled)
	}

	// Start sweep goroutine for expired rate limit counters.
	pe.startSweep()

	ruleCount := len(pe.rules)
	enabledCount := 0
	rlCount := 0
	for _, r := range pe.rules {
		if r.rule.Enabled {
			enabledCount++
		}
		if r.rule.Type == "rate_limit" {
			rlCount++
		}
	}
	pe.logger.Info("policy engine provisioned",
		zap.Int("rules", ruleCount),
		zap.Int("enabled", enabledCount),
		zap.Int("rate_limit_zones", rlCount),
		zap.String("rules_file", pe.RulesFile))

	return nil
}

func (pe *PolicyEngine) Validate() error {
	if pe.RulesFile == "" && len(pe.Rules) == 0 {
		return fmt.Errorf("either rules_file or inline rules must be configured")
	}
	return nil
}

func (pe *PolicyEngine) Cleanup() error {
	if pe.stopPoll != nil {
		close(pe.stopPoll)
	}
	if pe.stopSweep != nil {
		close(pe.stopSweep)
	}
	// Note: pe.rlState is intentionally NOT nilled here. ServeHTTP reads
	// pe.rlState without holding mu (it's set once in Provision and never
	// changed), so nilling it here would introduce a data race with
	// in-flight requests. The GC will collect it after the handler is
	// dereferenced by Caddy.
	return nil
}

// ─── ServeHTTP ──────────────────────────────────────────────────────

func (pe *PolicyEngine) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyhttp.Handler) error {
	pe.mu.RLock()
	rules := pe.rules
	globalCfg := pe.rlGlobalConfig
	respHeaders := pe.respHeaders
	pe.mu.RUnlock()

	// ── 4-pass evaluation ──────────────────────────────────────────
	//
	// Pass 1 — Deny list: block/honeypot rules terminate immediately (403).
	// Pass 2 — Allow: first allow match sets the "skip WAF" flag but does NOT
	//          terminate — evaluation continues to passes 3 & 4.
	// Pass 3 — Detect: accumulate anomaly scores. Skipped if allow matched.
	// Pass 4 — Rate limit: always evaluates regardless of allow. Counters
	//          always tick. Exceeded deny-action → 429.
	//
	// Rules are sorted by priority (block < detect < allow < rate_limit), so a
	// single loop handles all four passes in order. Allow skips further detect
	// rules (allowed traffic isn't scored). Rate limits apply independently.
	//
	// After the loop: if accumulated score > threshold → 403 (detect_block).

	pe.mu.RLock()
	wafCfg := pe.wafConfig
	pe.mu.RUnlock()

	var pb *parsedBody
	var bodyRead bool
	var allowMatched bool
	var scorer scoreAccumulator

	// Resolve per-service WAF config for this request.
	host := stripPort(r.Host)
	servicePL, serviceThreshold := resolveWafConfig(wafCfg, host)

	for _, cr := range rules {
		if !cr.rule.Enabled {
			continue
		}

		// Rate limit and detect rules may have service matching.
		if (cr.rule.Type == "rate_limit" || cr.rule.Type == "detect") && !matchService(cr.rule.Service, r) {
			continue
		}

		// If an allow already matched, skip further allow AND detect rules.
		// Allowed traffic bypasses scoring entirely.
		if allowMatched && (cr.rule.Type == "allow" || cr.rule.Type == "detect") {
			continue
		}

		// Detect rules: skip if paranoia level is too high for this service.
		if cr.rule.Type == "detect" && cr.rule.ParanoiaLevel > 0 && cr.rule.ParanoiaLevel > servicePL {
			continue
		}

		// Lazy body read: only when a rule needs body fields and we haven't read yet.
		if cr.needsBody && !bodyRead {
			if r.Body != nil && r.Body != http.NoBody {
				buf, err := readBody(r, pe.BodyMaxSize)
				if err != nil {
					pe.logger.Debug("failed to read request body", zap.Error(err))
				}
				pb = &parsedBody{raw: buf}
			} else {
				pb = &parsedBody{}
			}
			bodyRead = true
		}

		// For detect rules, use detailed matching to capture match data.
		// For all other types, use the fast non-detailed path.
		var detectDetails []matchDetail
		if cr.rule.Type == "detect" {
			matched, details := matchRuleDetailed(cr, r, pb)
			if !matched {
				continue
			}
			detectDetails = details
		} else {
			if !matchRule(cr, r, pb) {
				continue
			}
		}

		// Rule matched — take action.
		switch cr.rule.Type {
		case "allow":
			// Pass 2: set allow flag and Caddy vars, but do NOT return.
			// Rate limit rules (pass 4) still need to be evaluated.
			caddyhttp.SetVar(r.Context(), "policy_engine.action", "allow")
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
			if len(cr.rule.Tags) > 0 {
				caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
			}
			pe.logger.Info("policy allow",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.Strings("tags", cr.rule.Tags),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			allowMatched = true
			// Continue — don't return. Rate limits still apply.

		case "block", "honeypot":
			// Pass 1: deny list — hard terminate.
			caddyhttp.SetVar(r.Context(), "policy_engine.action", cr.rule.Type)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
			if len(cr.rule.Tags) > 0 {
				caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
			}
			// Capture full request context for investigation.
			captureRequestContext(r, pb)
			if !pe.HideHeaders {
				w.Header().Set("X-Blocked-By", "policy-engine")
				w.Header().Set("X-Blocked-Rule", cr.rule.Name)
				if len(cr.rule.Tags) > 0 {
					w.Header().Set("X-Policy-Tags", strings.Join(cr.rule.Tags, ","))
				}
			}
			pe.logger.Info("policy block",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.String("type", cr.rule.Type),
				zap.Strings("tags", cr.rule.Tags),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return caddyhttp.Error(http.StatusForbidden, nil)

		case "detect":
			// Pass 3: anomaly scoring — accumulate score, don't terminate.
			scorer.inbound += cr.score
			scorer.matched = append(scorer.matched, matchedRule{
				ruleID:   cr.rule.ID,
				ruleName: cr.rule.Name,
				severity: cr.rule.Severity,
				score:    cr.score,
				matches:  detectDetails,
			})
			pe.logger.Debug("detect rule matched",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.String("severity", cr.rule.Severity),
				zap.Int("score", cr.score),
				zap.Int("cumulative", scorer.inbound),
				zap.Int("match_details", len(detectDetails)),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))

		case "rate_limit":
			// Pass 4: rate limit — always evaluated, even if allow matched.
			if cr.rlConfig == nil || pe.rlState == nil {
				continue
			}

			z := pe.rlState.getZone(cr.rule.ID)
			if z == nil {
				continue
			}

			key := resolveRateLimitKey(cr.rlConfig.Key, r, pb)
			if key == "" {
				continue
			}

			allowed, count, limit := z.allow(key, time.Now())
			remaining := limit - int(count)

			if cr.rlConfig.Action == "log_only" {
				if !pe.HideHeaders {
					setRateLimitHeaders(w, limit, remaining, cr.rlConfig.parsedWindow, cr.rule.Name)
					w.Header().Set("X-RateLimit-Monitor", cr.rule.Name)
				}
				caddyhttp.SetVar(r.Context(), "policy_engine.action", "rate_limit_monitor")
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
				continue
			}

			if !allowed {
				caddyhttp.SetVar(r.Context(), "policy_engine.action", "rate_limit")
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
				caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
				if len(cr.rule.Tags) > 0 {
					caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(cr.rule.Tags, ","))
				}
				rlHeaderName := cr.rule.Name
				if pe.HideHeaders {
					rlHeaderName = ""
				}
				setRateLimitHeaders(w, limit, 0, cr.rlConfig.parsedWindow, rlHeaderName)

				jitter := float64(0)
				if globalCfg != nil {
					jitter = globalCfg.jitter
				}
				w.Header().Set("Retry-After", retryAfterSeconds(cr.rlConfig.parsedWindow, jitter))

				pe.logger.Info("rate limited",
					zap.String("rule_id", cr.rule.ID),
					zap.String("rule_name", cr.rule.Name),
					zap.String("key", key),
					zap.Int64("count", count),
					zap.Int("limit", limit),
					zap.Strings("tags", cr.rule.Tags),
					zap.String("client_ip", clientIP(r)),
					zap.String("uri", r.RequestURI))
				return caddyhttp.Error(http.StatusTooManyRequests, nil)
			}

			if !pe.HideHeaders {
				setRateLimitHeaders(w, limit, remaining, cr.rlConfig.parsedWindow, cr.rule.Name)
			}
		}
	}

	// ── Post-loop: anomaly threshold check ─────────────────────────
	// If detect rules fired and the accumulated score exceeds the threshold,
	// block the request. This happens after all rules (including rate limits)
	// have been evaluated, so rate limit counters are always ticked.
	if scorer.inbound > 0 && !allowMatched {
		// Set score variables regardless of whether threshold is exceeded.
		caddyhttp.SetVar(r.Context(), "policy_engine.anomaly_score", strconv.Itoa(scorer.inbound))
		caddyhttp.SetVar(r.Context(), "policy_engine.anomaly_threshold", strconv.Itoa(serviceThreshold))
		caddyhttp.SetVar(r.Context(), "policy_engine.matched_rules", strconv.Itoa(len(scorer.matched)))

		// Always emit match details for all detect events (both blocking and logged).
		// This enables observability for below-threshold events too.
		matchesJSON := serializeDetectMatches(scorer.matched)
		if matchesJSON != "" {
			caddyhttp.SetVar(r.Context(), "policy_engine.detect_matches", matchesJSON)
		}

		if scorer.inbound >= serviceThreshold && serviceThreshold > 0 {
			caddyhttp.SetVar(r.Context(), "policy_engine.action", "detect_block")
			// Capture full request context for investigation.
			captureRequestContext(r, pb)

			// Build matched-rule detail strings for logging and access log capture.
			ruleNames := make([]string, 0, len(scorer.matched))
			ruleDetails := make([]string, 0, len(scorer.matched))
			var tags []string
			tagSeen := map[string]bool{}
			for _, m := range scorer.matched {
				ruleNames = append(ruleNames, m.ruleID)
				// Format: "PE-920350:WARNING:3" (id:severity:score)
				ruleDetails = append(ruleDetails, m.ruleID+":"+m.severity+":"+strconv.Itoa(m.score))
				// Collect unique tags from all matched detect rules.
				// Tags aren't stored on matchedRule, so we look them up from compiled rules.
			}
			// Look up tags from compiled rules for all matched detect rules.
			// Use the local `rules` snapshot (captured at function start) —
			// no lock needed since it's already a slice copy.
			for _, m := range scorer.matched {
				for _, cr := range rules {
					if cr.rule.ID == m.ruleID {
						for _, t := range cr.rule.Tags {
							if !tagSeen[t] {
								tagSeen[t] = true
								tags = append(tags, t)
							}
						}
						break
					}
				}
			}

			// Set Caddy vars for access log capture (matches block/allow pattern).
			summary := fmt.Sprintf("Detect Block (score %d/%d, %d rules)", scorer.inbound, serviceThreshold, len(scorer.matched))
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", summary)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", strings.Join(ruleNames, ","))
			caddyhttp.SetVar(r.Context(), "policy_engine.detect_rules", strings.Join(ruleDetails, ","))
			if len(tags) > 0 {
				caddyhttp.SetVar(r.Context(), "policy_engine.tags", strings.Join(tags, ","))
			}

			if !pe.HideHeaders {
				w.Header().Set("X-Blocked-By", "policy-engine")
				w.Header().Set("X-Anomaly-Score", strconv.Itoa(scorer.inbound))
				w.Header().Set("X-Blocked-Rule", summary)
				w.Header().Set("X-Detect-Rules", strings.Join(ruleDetails, " "))
			}
			pe.logger.Info("anomaly threshold exceeded",
				zap.Int("score", scorer.inbound),
				zap.Int("threshold", serviceThreshold),
				zap.Int("rules_matched", len(scorer.matched)),
				zap.Strings("rule_ids", ruleNames),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return caddyhttp.Error(http.StatusForbidden, nil)
		}
	}

	// Apply response headers (CSP + security) before passing to next handler.
	// This wraps the ResponseWriter when "default" mode CSP or header removal
	// requires intercepting WriteHeader(). Must happen after rule evaluation
	// (block/rate_limit return early above) and before next.ServeHTTP().
	w = applyResponseHeaders(w, r.Host, respHeaders)

	// Pass through to next handler. If allowMatched is true, the Caddyfile
	// @needs_waf matcher will see policy_engine.action=allow and skip WAF.
	return next.ServeHTTP(w, r)
}

// ─── Body Reading ───────────────────────────────────────────────────

// readBody reads up to maxSize bytes from r.Body and re-wraps the body
// so downstream handlers still see the full content.
// Pattern borrowed from github.com/erfianugrah/caddy-body-matcher.
func readBody(r *http.Request, maxSize int64) ([]byte, error) {
	lr := io.LimitReader(r.Body, maxSize+1)
	buf, err := io.ReadAll(lr)
	if err != nil {
		// Re-wrap partial data + remaining original body.
		r.Body = io.NopCloser(io.MultiReader(bytes.NewReader(buf), r.Body))
		return nil, err
	}

	if int64(len(buf)) > maxSize {
		// Body exceeds limit — re-assemble full body for downstream,
		// but only use first maxSize bytes for matching.
		r.Body = io.NopCloser(io.MultiReader(bytes.NewReader(buf), r.Body))
		buf = buf[:maxSize]
	} else {
		// Body fully consumed — replace with buffered copy.
		r.Body = io.NopCloser(bytes.NewReader(buf))
	}

	return buf, nil
}

// ─── Rule Matching ──────────────────────────────────────────────────

func matchRule(cr compiledRule, r *http.Request, pb *parsedBody) bool {
	if len(cr.conditions) == 0 {
		// No conditions = matches all requests.
		return true
	}

	if cr.rule.GroupOp == "or" {
		for _, cc := range cr.conditions {
			if matchCondition(cc, r, pb) {
				return true
			}
		}
		return false
	}

	// Default: AND — all conditions must match.
	for _, cc := range cr.conditions {
		if !matchCondition(cc, r, pb) {
			return false
		}
	}
	return true
}

func matchCondition(cc compiledCondition, r *http.Request, pb *parsedBody) bool {
	// Special handling for "exists" operator on body_json — checks field presence,
	// not string comparison.
	if cc.isExists {
		result := extractFieldExists(cc, pb)
		if cc.negate {
			return !result
		}
		return result
	}

	// count: pseudo-field — count values in a collection, compare numerically.
	if cc.isCount {
		count := countMultiField(cc.countField, r, pb)
		target := strconv.Itoa(count)
		result := evalOperator(cc, target)
		if cc.negate {
			return !result
		}
		return result
	}

	// Multi-value fields (all_args, all_headers, all_cookies, etc.) —
	// iterate all values, return true if ANY matches (OR semantics).
	if cc.isMulti {
		values := extractMultiField(cc, r, pb)
		for _, val := range values {
			if len(cc.transforms) > 0 {
				val = applyTransforms(val, cc.transforms)
			}
			if evalOperator(cc, val) {
				if cc.negate {
					return false // negate + any match = fail (NOT-ANY = ALL-NOT)
				}
				return true
			}
		}
		// No value matched.
		if cc.negate {
			return true // negate + no match = pass (NOT-ANY when none matched)
		}
		return false
	}

	target := extractField(cc, r, pb)

	// Apply transforms before operator evaluation.
	if len(cc.transforms) > 0 {
		target = applyTransforms(target, cc.transforms)
	}

	result := evalOperator(cc, target)
	if cc.negate {
		return !result
	}
	return result
}

// extractField gets the request value for a condition's field.
//
// Field semantics:
//   - "path":     full request URI including query string (r.URL.RequestURI())
//   - "uri_path": path component only, without query string (r.URL.Path)
//
// These are intentionally distinct — "path" matches the full URI for backward
// compatibility with wafctl-generated rules that need query string matching.
func extractField(cc compiledCondition, r *http.Request, pb *parsedBody) string {
	switch cc.field {
	case "ip":
		return clientIP(r)
	case "path":
		// NOTE: "path" includes the query string (full request URI).
		// Use "uri_path" for path-only matching without query string.
		return r.URL.RequestURI()
	case "uri_path":
		return r.URL.Path
	case "request_basename":
		// CRS REQUEST_BASENAME: filename portion of the URI path.
		p := r.URL.Path
		if idx := strings.LastIndexByte(p, '/'); idx >= 0 {
			return p[idx+1:]
		}
		return p
	case "host":
		return r.Host
	case "method":
		return r.Method
	case "user_agent":
		return r.Header.Get("User-Agent")
	case "query":
		return r.URL.RawQuery
	case "country":
		return r.Header.Get("Cf-Ipcountry")
	case "referer":
		return r.Header.Get("Referer")
	case "http_version":
		return r.Proto
	case "header":
		if cc.name != "" {
			return r.Header.Get(cc.name)
		}
		return ""
	case "cookie":
		if cc.name != "" {
			if c, err := r.Cookie(cc.name); err == nil {
				return c.Value
			}
		}
		return ""
	case "args":
		if cc.name != "" {
			return r.URL.Query().Get(cc.name)
		}
		return ""
	case "body":
		if pb != nil {
			return string(pb.raw)
		}
		return ""
	case "body_json":
		if pb == nil {
			return ""
		}
		if cc.name != "" && len(pb.raw) > 0 {
			root, ok := pb.getJSON()
			if !ok {
				return ""
			}
			val, found := resolveJSONPathParsed(root, cc.name)
			if !found {
				return ""
			}
			return jsonValueToString(val)
		}
		return string(pb.raw)
	case "body_form":
		if pb == nil {
			return ""
		}
		if cc.name != "" && len(pb.raw) > 0 {
			values := pb.getForm()
			if values == nil {
				return ""
			}
			if fv, ok := values[cc.name]; ok && len(fv) > 0 {
				return fv[0]
			}
		}
		return ""
	default:
		return ""
	}
}

// extractFieldExists checks whether a body_json field exists (for the "exists" operator).
func extractFieldExists(cc compiledCondition, pb *parsedBody) bool {
	if cc.field != "body_json" || cc.name == "" || pb == nil || len(pb.raw) == 0 {
		return false
	}
	root, ok := pb.getJSON()
	if !ok {
		return false
	}
	_, found := resolveJSONPathParsed(root, cc.name)
	return found
}

// extractMultiField returns all values for an aggregate field.
// Used by matchCondition when cc.isMulti is true.
func extractMultiField(cc compiledCondition, r *http.Request, pb *parsedBody) []string {
	switch cc.field {
	case "all_args":
		// All query + POST params: names AND values (matches CRS ARGS|ARGS_NAMES)
		var vals []string
		for k, vs := range r.URL.Query() {
			vals = append(vals, k)
			vals = append(vals, vs...)
		}
		if pb != nil {
			for k, vs := range pb.getForm() {
				vals = append(vals, k)
				vals = append(vals, vs...)
			}
		}
		return vals

	case "all_args_values":
		// All query + POST param values only (matches CRS ARGS)
		var vals []string
		for _, vs := range r.URL.Query() {
			vals = append(vals, vs...)
		}
		if pb != nil {
			for _, vs := range pb.getForm() {
				vals = append(vals, vs...)
			}
		}
		return vals

	case "all_args_names":
		// All query + POST param names (matches CRS ARGS_NAMES)
		var vals []string
		for k := range r.URL.Query() {
			vals = append(vals, k)
		}
		if pb != nil {
			for k := range pb.getForm() {
				vals = append(vals, k)
			}
		}
		return vals

	case "all_headers":
		// All request header values (matches CRS REQUEST_HEADERS)
		var vals []string
		for _, vs := range r.Header {
			vals = append(vals, vs...)
		}
		return vals

	case "all_headers_names":
		// All request header names (matches CRS REQUEST_HEADERS_NAMES)
		var vals []string
		for k := range r.Header {
			vals = append(vals, k)
		}
		return vals

	case "all_cookies":
		// All cookie values (matches CRS REQUEST_COOKIES)
		var vals []string
		for _, c := range r.Cookies() {
			vals = append(vals, c.Value)
		}
		return vals

	case "all_cookies_names":
		// All cookie names (matches CRS REQUEST_COOKIES_NAMES)
		var vals []string
		for _, c := range r.Cookies() {
			vals = append(vals, c.Name)
		}
		return vals

	default:
		return nil
	}
}

// extractMultiFieldKeyed returns key-value pairs from multi-value fields,
// preserving which specific parameter/header/cookie matched.
// Key is the Coraza-style variable name (e.g., "ARGS:username", "REQUEST_HEADERS:User-Agent").
func extractMultiFieldKeyed(cc compiledCondition, r *http.Request, pb *parsedBody) []keyedValue {
	switch cc.field {
	case "all_args":
		var kvs []keyedValue
		for k, vs := range r.URL.Query() {
			kvs = append(kvs, keyedValue{key: "ARGS_NAMES:" + k, val: k})
			for _, v := range vs {
				kvs = append(kvs, keyedValue{key: "ARGS:" + k, val: v})
			}
		}
		if pb != nil {
			for k, vs := range pb.getForm() {
				kvs = append(kvs, keyedValue{key: "ARGS_POST_NAMES:" + k, val: k})
				for _, v := range vs {
					kvs = append(kvs, keyedValue{key: "ARGS_POST:" + k, val: v})
				}
			}
		}
		return kvs

	case "all_args_values":
		var kvs []keyedValue
		for k, vs := range r.URL.Query() {
			for _, v := range vs {
				kvs = append(kvs, keyedValue{key: "ARGS:" + k, val: v})
			}
		}
		if pb != nil {
			for k, vs := range pb.getForm() {
				for _, v := range vs {
					kvs = append(kvs, keyedValue{key: "ARGS_POST:" + k, val: v})
				}
			}
		}
		return kvs

	case "all_args_names":
		var kvs []keyedValue
		for k := range r.URL.Query() {
			kvs = append(kvs, keyedValue{key: "ARGS_NAMES", val: k})
		}
		if pb != nil {
			for k := range pb.getForm() {
				kvs = append(kvs, keyedValue{key: "ARGS_POST_NAMES", val: k})
			}
		}
		return kvs

	case "all_headers":
		var kvs []keyedValue
		for k, vs := range r.Header {
			for _, v := range vs {
				kvs = append(kvs, keyedValue{key: "REQUEST_HEADERS:" + k, val: v})
			}
		}
		return kvs

	case "all_headers_names":
		var kvs []keyedValue
		for k := range r.Header {
			kvs = append(kvs, keyedValue{key: "REQUEST_HEADERS_NAMES", val: k})
		}
		return kvs

	case "all_cookies":
		var kvs []keyedValue
		for _, c := range r.Cookies() {
			kvs = append(kvs, keyedValue{key: "REQUEST_COOKIES:" + c.Name, val: c.Value})
		}
		return kvs

	case "all_cookies_names":
		var kvs []keyedValue
		for _, c := range r.Cookies() {
			kvs = append(kvs, keyedValue{key: "REQUEST_COOKIES_NAMES", val: c.Name})
		}
		return kvs

	default:
		return nil
	}
}

// countMultiField returns the count of values for a given field.
// Used by the count: pseudo-field.
func countMultiField(field string, r *http.Request, pb *parsedBody) int {
	cc := compiledCondition{field: field}
	return len(extractMultiField(cc, r, pb))
}

// evalOperator evaluates the operator against the extracted target value.
// The negate flag is handled by the caller (matchCondition).
func evalOperator(cc compiledCondition, target string) bool {
	switch cc.operator {
	case "eq":
		return target == cc.exactVal
	case "neq":
		// neq returns the *equality* result here; the negate flag on the
		// compiledCondition (set during compilation for neq/not_ip_match/
		// not_in_list) causes matchCondition to invert this result.
		// This two-step pattern keeps evalOperator focused on positive
		// matching while matchCondition handles all negation uniformly.
		return target == cc.exactVal
	case "contains":
		return strings.Contains(target, cc.contains)
	case "begins_with":
		return strings.HasPrefix(target, cc.prefix)
	case "ends_with":
		return strings.HasSuffix(target, cc.suffix)
	case "regex":
		if cc.regex != nil {
			return cc.regex.MatchString(target)
		}
		return false
	case "ip_match", "not_ip_match":
		return evalIPMatch(cc, target)
	case "in", "in_list":
		// in_list with ip kind uses IP-aware matching.
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			return evalIPMatch(cc, target)
		}
		return cc.stringSet[target]
	case "not_in_list":
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			return evalIPMatch(cc, target)
		}
		return cc.stringSet[target]
	case "phrase_match":
		if cc.acMatcher != nil {
			return cc.acMatcher.ContainsAny(target)
		}
		return false
	case "gt":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false
		}
		return v > cc.numericVal
	case "ge":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false
		}
		return v >= cc.numericVal
	case "lt":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false
		}
		return v < cc.numericVal
	case "le":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false
		}
		return v <= cc.numericVal
	case "validate_byte_range":
		return evalValidateByteRange(cc.byteRangeSet, target)
	case "validate_url_encoding":
		return evalValidateURLEncoding(target)
	case "detect_sqli":
		isSQLi, _ := libinjection.IsSQLi(target)
		return isSQLi
	case "detect_xss":
		return libinjection.IsXSS(target)
	default:
		return false
	}
}

// evalIPMatch checks if target IP is in the compiled IP set or CIDR ranges.
// Uses O(1) hash set for single IPs (ipSet), falls back to linear scan for CIDRs.
func evalIPMatch(cc compiledCondition, target string) bool {
	ip := net.ParseIP(target)
	if ip == nil {
		return false
	}
	// O(1) hash lookup for single IPs.
	if cc.ipSet != nil {
		var key [16]byte
		copy(key[:], ip.To16())
		if cc.ipSet[key] {
			return true
		}
	}
	// Linear scan for CIDR ranges (typically small count even in large lists).
	for _, n := range cc.ipNets {
		if n.Contains(ip) {
			return true
		}
	}
	return false
}

// ipTo16Key normalizes an IP to a 16-byte array key for hash set storage.
func ipTo16Key(ip net.IP) [16]byte {
	var key [16]byte
	copy(key[:], ip.To16())
	return key
}

// ─── Byte Range Validation ─────────────────────────────────────────

// parseByteRangeSet parses a CRS-style byte range spec (e.g., "9,10,13,32-126,128-255")
// into a 256-element boolean array where true means the byte value is allowed.
func parseByteRangeSet(spec string) (*[256]bool, error) {
	var set [256]bool
	for _, part := range strings.Split(spec, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if idx := strings.IndexByte(part, '-'); idx >= 0 {
			lo, err := strconv.Atoi(strings.TrimSpace(part[:idx]))
			if err != nil || lo < 0 || lo > 255 {
				return nil, fmt.Errorf("invalid byte value %q", part[:idx])
			}
			hi, err := strconv.Atoi(strings.TrimSpace(part[idx+1:]))
			if err != nil || hi < 0 || hi > 255 {
				return nil, fmt.Errorf("invalid byte value %q", part[idx+1:])
			}
			if lo > hi {
				return nil, fmt.Errorf("invalid range %d-%d: low > high", lo, hi)
			}
			for b := lo; b <= hi; b++ {
				set[b] = true
			}
		} else {
			v, err := strconv.Atoi(part)
			if err != nil || v < 0 || v > 255 {
				return nil, fmt.Errorf("invalid byte value %q", part)
			}
			set[v] = true
		}
	}
	return &set, nil
}

// evalValidateByteRange returns true if ALL bytes in target are within the
// allowed set. CRS semantics: @validateByteRange succeeds when the input
// contains only allowed bytes.
// evalValidateByteRange returns true if any byte in target is OUTSIDE the
// allowed set (i.e., a violation was found). This matches CRS/ModSecurity
// semantics where @validateByteRange fires when invalid bytes are present.
func evalValidateByteRange(set *[256]bool, target string) bool {
	if set == nil {
		return false
	}
	for i := 0; i < len(target); i++ {
		if !set[target[i]] {
			return true // violation: byte outside allowed range
		}
	}
	return false // all bytes valid
}

// ─── URL Encoding Validation ───────────────────────────────────────

// evalValidateURLEncoding returns true if any percent-encoded sequence in
// target is malformed (violation detected). This matches CRS/ModSecurity
// semantics where @validateUrlEncoding fires when invalid encoding is found.
// Non-encoded bytes are ignored (not violations).
func evalValidateURLEncoding(target string) bool {
	i := 0
	for i < len(target) {
		if target[i] == '%' {
			// Need at least 2 more characters.
			if i+2 >= len(target) {
				return true // violation: truncated %
			}
			if unhex(target[i+1]) < 0 || unhex(target[i+2]) < 0 {
				return true // violation: invalid hex digits
			}
			i += 3
		} else {
			i++
		}
	}
	return false // all encoding valid
}

// compileIPList compiles a list of IP/CIDR strings into an ipSet (for single IPs)
// and ipNets (for CIDR ranges). Single IPs go into the O(1) hash set;
// CIDRs that aren't /32 or /128 go into the linear-scan slice.
func compileIPList(items []string) (map[[16]byte]bool, []net.IPNet, error) {
	ipSet := make(map[[16]byte]bool, len(items))
	var nets []net.IPNet

	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		if strings.Contains(item, "/") {
			_, ipNet, err := net.ParseCIDR(item)
			if err != nil {
				return nil, nil, fmt.Errorf("parsing CIDR %q: %w", item, err)
			}
			// Check if this is a single-host CIDR (/32 or /128).
			ones, bits := ipNet.Mask.Size()
			if ones == bits {
				// Single host — put in hash set.
				ipSet[ipTo16Key(ipNet.IP)] = true
			} else {
				nets = append(nets, *ipNet)
			}
		} else {
			ip := net.ParseIP(item)
			if ip == nil {
				return nil, nil, fmt.Errorf("parsing IP %q: invalid address", item)
			}
			ipSet[ipTo16Key(ip)] = true
		}
	}

	return ipSet, nets, nil
}

// ─── Detailed Matching (Observability) ──────────────────────────────

const maxLogValueLen = 200

// truncateForLog truncates a string to maxLogValueLen for safe logging.
func truncateForLog(s string) string {
	if len(s) <= maxLogValueLen {
		return s
	}
	return s[:maxLogValueLen] + "..."
}

// singleFieldVarName maps a single-value field + optional name to a
// Coraza-style variable name (e.g., "header"+"User-Agent" → "REQUEST_HEADERS:User-Agent").
func singleFieldVarName(field, name string) string {
	switch field {
	case "ip":
		return "REMOTE_ADDR"
	case "path":
		return "REQUEST_URI"
	case "uri_path":
		return "REQUEST_FILENAME"
	case "host":
		return "SERVER_NAME"
	case "method":
		return "REQUEST_METHOD"
	case "user_agent":
		return "REQUEST_HEADERS:User-Agent"
	case "query":
		return "QUERY_STRING"
	case "country":
		return "REQUEST_HEADERS:Cf-Ipcountry"
	case "referer":
		return "REQUEST_HEADERS:Referer"
	case "http_version":
		return "REQUEST_PROTOCOL"
	case "header":
		if name != "" {
			return "REQUEST_HEADERS:" + name
		}
		return "REQUEST_HEADERS"
	case "cookie":
		if name != "" {
			return "REQUEST_COOKIES:" + name
		}
		return "REQUEST_COOKIES"
	case "args":
		if name != "" {
			return "ARGS:" + name
		}
		return "ARGS"
	case "body":
		return "REQUEST_BODY"
	case "body_json":
		if name != "" {
			return "REQUEST_BODY_JSON:" + name
		}
		return "REQUEST_BODY"
	case "body_form":
		if name != "" {
			return "ARGS_POST:" + name
		}
		return "ARGS_POST"
	default:
		return strings.ToUpper(field)
	}
}

// evalOperatorDetailed evaluates the operator and returns the matched data string.
// Returns (matched bool, matchedData string). The matchedData is the substring
// that the operator matched — regex group 0, phrase_match hit, or the literal value.
func evalOperatorDetailed(cc compiledCondition, target string) (bool, string) {
	switch cc.operator {
	case "eq":
		if target == cc.exactVal {
			return true, target
		}
		return false, ""
	case "neq":
		// neq returns the *equality* result; negate handled by caller.
		if target == cc.exactVal {
			return true, target
		}
		return false, ""
	case "contains":
		if strings.Contains(target, cc.contains) {
			return true, cc.contains
		}
		return false, ""
	case "begins_with":
		if strings.HasPrefix(target, cc.prefix) {
			return true, cc.prefix
		}
		return false, ""
	case "ends_with":
		if strings.HasSuffix(target, cc.suffix) {
			return true, cc.suffix
		}
		return false, ""
	case "regex":
		if cc.regex != nil {
			m := cc.regex.FindString(target)
			if m != "" {
				return true, m
			}
			// Regex can match empty string (e.g., "^$" on "").
			if cc.regex.MatchString(target) {
				return true, ""
			}
		}
		return false, ""
	case "ip_match", "not_ip_match":
		if evalIPMatch(cc, target) {
			return true, target
		}
		return false, ""
	case "in", "in_list":
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			if evalIPMatch(cc, target) {
				return true, target
			}
			return false, ""
		}
		if cc.stringSet[target] {
			return true, target
		}
		return false, ""
	case "not_in_list":
		if cc.ipSet != nil || (cc.ipNets != nil && cc.stringSet == nil) {
			if evalIPMatch(cc, target) {
				return true, target
			}
			return false, ""
		}
		if cc.stringSet[target] {
			return true, target
		}
		return false, ""
	case "phrase_match":
		if cc.acMatcher != nil {
			if pattern, found := cc.acMatcher.FindFirst(target); found {
				return true, pattern
			}
		}
		return false, ""
	case "gt":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false, ""
		}
		if v > cc.numericVal {
			return true, target
		}
		return false, ""
	case "ge":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false, ""
		}
		if v >= cc.numericVal {
			return true, target
		}
		return false, ""
	case "lt":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false, ""
		}
		if v < cc.numericVal {
			return true, target
		}
		return false, ""
	case "le":
		v, err := strconv.ParseFloat(target, 64)
		if err != nil {
			return false, ""
		}
		if v <= cc.numericVal {
			return true, target
		}
		return false, ""
	case "validate_byte_range":
		if evalValidateByteRange(cc.byteRangeSet, target) {
			return true, ""
		}
		// Report the first offending byte for diagnostics.
		if cc.byteRangeSet != nil {
			for i := 0; i < len(target); i++ {
				if !cc.byteRangeSet[target[i]] {
					return false, fmt.Sprintf("byte 0x%02x at position %d", target[i], i)
				}
			}
		}
		return false, ""
	case "validate_url_encoding":
		if evalValidateURLEncoding(target) {
			return true, ""
		}
		return false, target
	case "detect_sqli":
		isSQLi, fingerprint := libinjection.IsSQLi(target)
		if isSQLi {
			return true, fingerprint
		}
		return false, ""
	case "detect_xss":
		if libinjection.IsXSS(target) {
			return true, target
		}
		return false, ""
	default:
		return false, ""
	}
}

// matchConditionDetailed evaluates a condition and returns the match detail
// on success. Returns (matched bool, detail *matchDetail).
// For multi-value fields, reports the FIRST matching value (same as Coraza's
// MATCHED_VAR which captures the first matching variable).
func matchConditionDetailed(cc compiledCondition, r *http.Request, pb *parsedBody) (bool, *matchDetail) {
	// Special handling for "exists" operator on body_json.
	if cc.isExists {
		result := extractFieldExists(cc, pb)
		if cc.negate {
			result = !result
		}
		if result {
			return true, &matchDetail{
				Field:    cc.field,
				VarName:  singleFieldVarName(cc.field, cc.name),
				Operator: cc.operator,
			}
		}
		return false, nil
	}

	// count: pseudo-field.
	if cc.isCount {
		count := countMultiField(cc.countField, r, pb)
		target := strconv.Itoa(count)
		matched, matchedData := evalOperatorDetailed(cc, target)
		if cc.negate {
			matched = !matched
		}
		if matched {
			return true, &matchDetail{
				Field:       "count:" + cc.countField,
				VarName:     "&" + strings.ToUpper(cc.countField),
				Value:       truncateForLog(target),
				MatchedData: truncateForLog(matchedData),
				Operator:    cc.operator,
			}
		}
		return false, nil
	}

	// Multi-value fields — iterate all, report first match.
	if cc.isMulti {
		kvs := extractMultiFieldKeyed(cc, r, pb)
		for _, kv := range kvs {
			val := kv.val
			if len(cc.transforms) > 0 {
				val = applyTransforms(val, cc.transforms)
			}
			matched, matchedData := evalOperatorDetailed(cc, val)
			if matched {
				if cc.negate {
					return false, nil // negate + any match = fail
				}
				return true, &matchDetail{
					Field:       cc.field,
					VarName:     kv.key,
					Value:       truncateForLog(kv.val), // original pre-transform value
					MatchedData: truncateForLog(matchedData),
					Operator:    cc.operator,
				}
			}
		}
		// No value matched.
		if cc.negate {
			return true, &matchDetail{
				Field:    cc.field,
				VarName:  strings.ToUpper(cc.field),
				Operator: cc.operator,
			}
		}
		return false, nil
	}

	// Single-value field.
	target := extractField(cc, r, pb)
	origTarget := target

	if len(cc.transforms) > 0 {
		target = applyTransforms(target, cc.transforms)
	}

	matched, matchedData := evalOperatorDetailed(cc, target)
	if cc.negate {
		matched = !matched
	}
	if matched {
		return true, &matchDetail{
			Field:       cc.field,
			VarName:     singleFieldVarName(cc.field, cc.name),
			Value:       truncateForLog(origTarget),
			MatchedData: truncateForLog(matchedData),
			Operator:    cc.operator,
		}
	}
	return false, nil
}

// matchRuleDetailed evaluates a rule and returns per-condition match details.
// Returns (matched bool, details []matchDetail).
func matchRuleDetailed(cr compiledRule, r *http.Request, pb *parsedBody) (bool, []matchDetail) {
	if len(cr.conditions) == 0 {
		return true, nil
	}

	if cr.rule.GroupOp == "or" {
		// OR: return on first match.
		for _, cc := range cr.conditions {
			matched, detail := matchConditionDetailed(cc, r, pb)
			if matched {
				if detail != nil {
					return true, []matchDetail{*detail}
				}
				return true, nil
			}
		}
		return false, nil
	}

	// AND: all must match, collect all details.
	var details []matchDetail
	for _, cc := range cr.conditions {
		matched, detail := matchConditionDetailed(cc, r, pb)
		if !matched {
			return false, nil
		}
		if detail != nil {
			details = append(details, *detail)
		}
	}
	return true, details
}

// detectMatchEntry is the JSON-serializable format for a matched detect rule
// with its per-condition match details. Emitted as a JSON array in the
// policy_engine.detect_matches Caddy variable for access log capture.
type detectMatchEntry struct {
	RuleID   string        `json:"rule_id"`
	RuleName string        `json:"rule_name,omitempty"`
	Severity string        `json:"severity"`
	Score    int           `json:"score"`
	Matches  []matchDetail `json:"matches,omitempty"`
}

// serializeDetectMatches converts matched detect rules into a compact JSON string.
// Returns "" if there are no matches worth serializing.
func serializeDetectMatches(matched []matchedRule) string {
	if len(matched) == 0 {
		return ""
	}

	entries := make([]detectMatchEntry, 0, len(matched))
	for _, m := range matched {
		entries = append(entries, detectMatchEntry{
			RuleID:   m.ruleID,
			RuleName: m.ruleName,
			Severity: m.severity,
			Score:    m.score,
			Matches:  m.matches,
		})
	}

	buf, err := json.Marshal(entries)
	if err != nil {
		return ""
	}
	return string(buf)
}

// ─── Request Context Capture ────────────────────────────────────────

// maxRequestBodyLog is the max bytes of request body to include in log capture.
const maxRequestBodyLog = 8192 // 8 KB

// serializeRequestHeaders converts request headers to a compact JSON string
// for access log capture. Strips large cookie values and caps total size.
func serializeRequestHeaders(r *http.Request) string {
	if len(r.Header) == 0 {
		return ""
	}
	// Copy headers, truncating oversized values (e.g., large cookies).
	hdr := make(map[string][]string, len(r.Header))
	for k, vs := range r.Header {
		vals := make([]string, len(vs))
		for i, v := range vs {
			if len(v) > 500 {
				vals[i] = v[:500] + "...(truncated)"
			} else {
				vals[i] = v
			}
		}
		hdr[k] = vals
	}
	buf, err := json.Marshal(hdr)
	if err != nil {
		return ""
	}
	return string(buf)
}

// captureRequestContext sets Caddy variables with the full request headers
// and (optionally) a truncated request body excerpt. Only called for
// block/honeypot/detect_block events — not on every request.
func captureRequestContext(r *http.Request, pb *parsedBody) {
	if hdrs := serializeRequestHeaders(r); hdrs != "" {
		caddyhttp.SetVar(r.Context(), "policy_engine.request_headers", hdrs)
	}
	// Include request body excerpt if it was already read for body conditions.
	// We don't read the body just for logging — only capture what's available.
	if pb != nil && len(pb.raw) > 0 {
		excerpt := pb.raw
		if len(excerpt) > maxRequestBodyLog {
			excerpt = excerpt[:maxRequestBodyLog]
		}
		caddyhttp.SetVar(r.Context(), "policy_engine.request_body", string(excerpt))
	}
}

// ─── JSON Helpers ───────────────────────────────────────────────────

// resolveJSONPath walks a dot-path like ".user.roles.0" through parsed JSON.
// Leading dot is optional. Returns (value, found).
// This variant parses from raw bytes — use resolveJSONPathParsed when
// you have a pre-parsed root (to avoid re-parsing per condition).
func resolveJSONPath(body []byte, dotPath string) (interface{}, bool) {
	var root interface{}
	if err := json.Unmarshal(body, &root); err != nil {
		return nil, false
	}
	return resolveJSONPathParsed(root, dotPath)
}

// resolveJSONPathParsed walks a dot-path through an already-parsed JSON value.
// Leading dot is optional. Returns (value, found).
func resolveJSONPathParsed(root interface{}, dotPath string) (interface{}, bool) {
	dotPath = strings.TrimPrefix(dotPath, ".")
	if dotPath == "" {
		return root, true
	}

	parts := strings.Split(dotPath, ".")
	current := root

	for _, part := range parts {
		switch v := current.(type) {
		case map[string]interface{}:
			val, ok := v[part]
			if !ok {
				return nil, false
			}
			current = val
		case []interface{}:
			idx, err := strconv.Atoi(part)
			if err != nil || idx < 0 || idx >= len(v) {
				return nil, false
			}
			current = v[idx]
		default:
			return nil, false
		}
	}

	return current, true
}

// jsonValueToString converts a JSON value to its string representation.
func jsonValueToString(v interface{}) string {
	switch val := v.(type) {
	case string:
		return val
	case float64:
		if val == float64(int64(val)) {
			return strconv.FormatInt(int64(val), 10)
		}
		return strconv.FormatFloat(val, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(val)
	case nil:
		return "null"
	default:
		b, err := json.Marshal(val)
		if err != nil {
			return fmt.Sprintf("%v", val)
		}
		return string(b)
	}
}

// ─── Client IP ──────────────────────────────────────────────────────

// clientIP extracts the client IP from the request, stripping the port.
func clientIP(r *http.Request) string {
	// Read the real client IP from Caddy's trusted_proxies-resolved variable.
	// This is set by Caddy's server layer before any handlers run, accounting
	// for X-Forwarded-For / CF-Connecting-IP headers from trusted proxies.
	// Falls back to r.RemoteAddr if the variable is not set (e.g., in tests).
	if val, ok := caddyhttp.GetVar(r.Context(), caddyhttp.ClientIPVarKey).(string); ok && val != "" {
		host, _, err := net.SplitHostPort(val)
		if err != nil {
			return val // no port
		}
		return host
	}
	// Fallback for non-Caddy contexts (unit tests, etc.).
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}

// ─── Rule Compilation ───────────────────────────────────────────────

func compileRules(rules []PolicyRule) ([]compiledRule, error) {
	var compiled []compiledRule
	for _, rule := range rules {
		cr, err := compileRule(rule)
		if err != nil {
			return nil, fmt.Errorf("rule %q (%s): %w", rule.Name, rule.ID, err)
		}
		compiled = append(compiled, cr)
	}

	// Sort by priority (lower first), then by ID for determinism.
	sort.Slice(compiled, func(i, j int) bool {
		if compiled[i].rule.Priority != compiled[j].rule.Priority {
			return compiled[i].rule.Priority < compiled[j].rule.Priority
		}
		return compiled[i].rule.ID < compiled[j].rule.ID
	})

	return compiled, nil
}

// validRuleTypes is the set of recognized rule types.
var validRuleTypes = map[string]bool{
	"allow":      true,
	"block":      true,
	"honeypot":   true,
	"rate_limit": true,
	"detect":     true,
}

// severityScores maps severity strings to anomaly score points.
// Matches the CRS scoring model exactly.
var severityScores = map[string]int{
	"CRITICAL": 5,
	"ERROR":    4,
	"WARNING":  3,
	"NOTICE":   2,
}

func compileRule(rule PolicyRule) (compiledRule, error) {
	cr := compiledRule{rule: rule}

	// Validate rule type early — unknown types would silently match
	// conditions but take no action in ServeHTTP.
	if !validRuleTypes[rule.Type] {
		return cr, fmt.Errorf("unsupported rule type %q (must be allow, block, honeypot, rate_limit, or detect)", rule.Type)
	}

	for _, cond := range rule.Conditions {
		cc, err := compileCondition(cond)
		if err != nil {
			return cr, fmt.Errorf("condition %s %s: %w", cond.Field, cond.Operator, err)
		}
		cr.conditions = append(cr.conditions, cc)
		if bodyFields[cond.Field] || needsBodyField(cond.Field) {
			cr.needsBody = true
		}
	}

	// Compile rate limit config if this is a rate_limit rule.
	if rule.Type == "rate_limit" {
		rlCfg, err := compileRLConfig(rule.RateLimit)
		if err != nil {
			return cr, fmt.Errorf("rate_limit config: %w", err)
		}
		cr.rlConfig = rlCfg
		if rlCfg.needsBody {
			cr.needsBody = true
		}
	}

	// Validate and compile detect rule severity → score.
	if rule.Type == "detect" {
		if rule.Severity == "" {
			return cr, fmt.Errorf("detect rules must have a severity (CRITICAL, ERROR, WARNING, NOTICE)")
		}
		score, ok := severityScores[rule.Severity]
		if !ok {
			return cr, fmt.Errorf("unknown severity %q (must be CRITICAL, ERROR, WARNING, or NOTICE)", rule.Severity)
		}
		cr.score = score
		if rule.ParanoiaLevel < 0 || rule.ParanoiaLevel > 4 {
			return cr, fmt.Errorf("paranoia_level must be 0-4, got %d", rule.ParanoiaLevel)
		}
	}

	return cr, nil
}

// ─── WAF Config Compilation ─────────────────────────────────────────

// compileWafConfig pre-compiles the WAF config for O(1) per-request lookup.
// Returns nil if no config is provided (anomaly scoring disabled).
func compileWafConfig(cfg *WafConfig) *compiledWafConfig {
	if cfg == nil {
		return nil
	}
	c := &compiledWafConfig{
		defaultPL:           cfg.ParanoiaLevel,
		defaultInThreshold:  cfg.InboundThreshold,
		defaultOutThreshold: cfg.OutboundThreshold,
	}
	// Sensible defaults.
	if c.defaultPL == 0 {
		c.defaultPL = 1
	}
	if c.defaultInThreshold == 0 {
		c.defaultInThreshold = 10
	}
	if c.defaultOutThreshold == 0 {
		c.defaultOutThreshold = 10
	}
	if len(cfg.PerService) > 0 {
		c.services = make(map[string]compiledWafServiceConfig, len(cfg.PerService))
		for host, svc := range cfg.PerService {
			cs := compiledWafServiceConfig{
				paranoiaLevel:    svc.ParanoiaLevel,
				inboundThreshold: svc.InboundThreshold,
			}
			// Zero means "inherit from defaults".
			if cs.paranoiaLevel == 0 {
				cs.paranoiaLevel = c.defaultPL
			}
			if cs.inboundThreshold == 0 {
				cs.inboundThreshold = c.defaultInThreshold
			}
			c.services[strings.ToLower(host)] = cs
		}
	}
	return c
}

// resolveWafConfig returns the effective paranoia level and inbound threshold
// for a given host. Falls back to defaults if no per-service override exists.
// Returns (1, 0) if wafConfig is nil (scoring disabled — PL 1, threshold 0
// meaning no blocking).
func resolveWafConfig(cfg *compiledWafConfig, host string) (paranoiaLevel, inboundThreshold int) {
	if cfg == nil {
		return 1, 0
	}
	if cfg.services != nil {
		if svc, ok := cfg.services[strings.ToLower(host)]; ok {
			return svc.paranoiaLevel, svc.inboundThreshold
		}
	}
	return cfg.defaultPL, cfg.defaultInThreshold
}

// stripPort removes the port from a host:port string.
func stripPort(host string) string {
	if h, _, err := net.SplitHostPort(host); err == nil {
		return h
	}
	return host
}

func compileCondition(cond PolicyCondition) (compiledCondition, error) {
	cc := compiledCondition{
		field:    cond.Field,
		operator: cond.Operator,
	}

	// Parse named fields: "Name:value" format.
	value := cond.Value
	switch cond.Field {
	case "header", "cookie", "args", "body_form":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	case "body_json":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	}

	// Handle negate operators (from operator name or explicit negate field).
	switch cond.Operator {
	case "neq", "not_ip_match", "not_in_list":
		cc.negate = true
	}
	// CRS !@ prefix: explicit negate field from converter output.
	if cond.Negate {
		cc.negate = !cc.negate // double-negate cancels (e.g., !neq = eq)
	}

	// Compile based on operator.
	switch cond.Operator {
	case "eq", "neq":
		cc.exactVal = value

	case "contains":
		cc.contains = value

	case "begins_with":
		cc.prefix = value

	case "ends_with":
		cc.suffix = value

	case "regex":
		if len(value) > maxRegexLen {
			return cc, fmt.Errorf("regex pattern too long (%d bytes, max %d)", len(value), maxRegexLen)
		}
		re, err := regexp.Compile(value)
		if err != nil {
			return cc, fmt.Errorf("invalid regex %q: %w", value, err)
		}
		cc.regex = re

	case "ip_match", "not_ip_match":
		nets, err := parseIPNets(value)
		if err != nil {
			return cc, fmt.Errorf("invalid IP/CIDR %q: %w", value, err)
		}
		cc.ipNets = nets

	case "in":
		// Accept both pipe-separated ("a|b|c") and space-separated ("a b c") values.
		// The wafctl frontend stores "in" values with pipes (PipeTagInput convention),
		// while some seeded rules use spaces. Normalize pipes to spaces, then split.
		cc.stringSet = make(map[string]bool)
		normalized := strings.ReplaceAll(value, "|", " ")
		for _, item := range strings.Fields(normalized) {
			cc.stringSet[item] = true
		}

	case "in_list", "not_in_list":
		// Managed list operators — items are pre-resolved by wafctl into ListItems.
		// ListKind determines how to compile: "ip" → ipSet + ipNets, everything else → stringSet.
		if cond.ListKind == "ip" {
			ipSet, nets, err := compileIPList(cond.ListItems)
			if err != nil {
				return cc, fmt.Errorf("compiling IP list: %w", err)
			}
			cc.ipSet = ipSet
			cc.ipNets = nets
		} else {
			cc.stringSet = make(map[string]bool, len(cond.ListItems))
			for _, item := range cond.ListItems {
				if item != "" {
					cc.stringSet[item] = true
				}
			}
		}

	case "exists":
		// "exists" checks for field presence (body_json dot-path).
		// No value comparison needed.
		cc.isExists = true

	case "phrase_match":
		// Aho-Corasick multi-pattern substring search.
		// Patterns come from ListItems (resolved by wafctl from managed lists or inline).
		if len(cond.ListItems) == 0 {
			return cc, fmt.Errorf("phrase_match requires list_items (pattern list)")
		}
		cc.acMatcher = CompileAC(cond.ListItems)

	case "gt", "ge", "lt", "le":
		// Numeric comparison operators.
		v, err := strconv.ParseFloat(value, 64)
		if err != nil {
			return cc, fmt.Errorf("numeric operator %q requires a numeric value, got %q: %w", cond.Operator, value, err)
		}
		cc.numericVal = v

	case "validate_byte_range":
		set, err := parseByteRangeSet(value)
		if err != nil {
			return cc, fmt.Errorf("invalid byte range %q: %w", value, err)
		}
		cc.byteRangeSet = set

	case "validate_url_encoding":
		// No compile-time state needed — validation is done at eval time.

	case "detect_sqli", "detect_xss":
		// No compile-time state needed — libinjection runs at eval time.

	default:
		return cc, fmt.Errorf("unsupported operator %q", cond.Operator)
	}

	// Detect aggregate fields — set isMulti for multi-value iteration in matchCondition.
	if multiFields[cc.field] {
		cc.isMulti = true
	}

	// Detect count: pseudo-field — "count:all_args", "count:all_headers", etc.
	if strings.HasPrefix(cond.Field, countPrefix) {
		underlying := cond.Field[len(countPrefix):]
		if !multiFields[underlying] {
			return cc, fmt.Errorf("count: requires an aggregate field, got %q (valid: all_args, all_args_values, all_args_names, all_headers, all_headers_names, all_cookies, all_cookies_names)", underlying)
		}
		cc.isCount = true
		cc.countField = underlying
		cc.isMulti = false // count produces a single value, not multi-iteration
	}

	// Resolve transform chain.
	for _, name := range cond.Transforms {
		fn, ok := transformRegistry[name]
		if !ok {
			return cc, fmt.Errorf("unknown transform %q (valid: %v)", name, validTransformNames())
		}
		cc.transforms = append(cc.transforms, fn)
	}

	return cc, nil
}

// parseIPNets parses a comma-or-space-separated list of IPs and CIDRs.
func parseIPNets(value string) ([]net.IPNet, error) {
	// Normalize: replace commas with spaces, then split.
	normalized := strings.ReplaceAll(value, ",", " ")
	tokens := strings.Fields(normalized)

	var nets []net.IPNet
	for _, tok := range tokens {
		if strings.Contains(tok, "/") {
			_, ipNet, err := net.ParseCIDR(tok)
			if err != nil {
				return nil, fmt.Errorf("parsing CIDR %q: %w", tok, err)
			}
			nets = append(nets, *ipNet)
		} else {
			ip := net.ParseIP(tok)
			if ip == nil {
				return nil, fmt.Errorf("parsing IP %q: invalid address", tok)
			}
			// Single IP → /32 or /128 mask.
			mask := net.CIDRMask(32, 32)
			if ip.To4() == nil {
				mask = net.CIDRMask(128, 128)
			}
			nets = append(nets, net.IPNet{IP: ip, Mask: mask})
		}
	}

	return nets, nil
}

// ─── Default Rules Merging ──────────────────────────────────────────

// mergeDefaultAndUserRules combines default rules with user rules.
// User rules override defaults with the same ID. Disabled default rule
// IDs are filtered out. The result is a combined slice ready for compilation.
func mergeDefaultAndUserRules(defaults, userRules []PolicyRule, disabledIDs []string) []PolicyRule {
	if len(defaults) == 0 {
		return userRules
	}

	// Build sets for O(1) lookup.
	disabledSet := make(map[string]bool, len(disabledIDs))
	for _, id := range disabledIDs {
		disabledSet[id] = true
	}
	userIDSet := make(map[string]bool, len(userRules))
	for _, r := range userRules {
		userIDSet[r.ID] = true
	}

	// Start with non-disabled, non-overridden defaults.
	merged := make([]PolicyRule, 0, len(defaults)+len(userRules))
	for _, r := range defaults {
		if disabledSet[r.ID] {
			continue // explicitly disabled
		}
		if userIDSet[r.ID] {
			continue // overridden by user rule
		}
		merged = append(merged, r)
	}

	// Append all user rules.
	merged = append(merged, userRules...)
	return merged
}

// loadDefaultRulesFile reads and parses the default rules JSON file.
// Returns nil, nil if the file does not exist (not an error — defaults are optional).
func loadDefaultRulesFile(path string) ([]PolicyRule, time.Time, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, time.Time{}, nil
		}
		return nil, time.Time{}, fmt.Errorf("opening default rules file: %w", err)
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return nil, time.Time{}, fmt.Errorf("stat default rules file: %w", err)
	}

	data, err := io.ReadAll(f)
	if err != nil {
		return nil, time.Time{}, fmt.Errorf("reading default rules file: %w", err)
	}

	var file DefaultRulesFile
	if err := json.Unmarshal(data, &file); err != nil {
		return nil, time.Time{}, fmt.Errorf("parsing default rules file: %w", err)
	}

	// Support both "rules" (legacy v6) and "default_rules" (CRS converter v7+).
	rules := file.Rules
	if len(rules) == 0 && len(file.DefaultRules) > 0 {
		rules = file.DefaultRules
	}

	return rules, info.ModTime(), nil
}

// ─── Hot Reload ─────────────────────────────────────────────────────

func (pe *PolicyEngine) pollForChanges() {
	ticker := time.NewTicker(time.Duration(pe.ReloadInterval))
	defer ticker.Stop()

	for {
		select {
		case <-pe.stopPoll:
			return
		case <-ticker.C:
			pe.checkReload()
		}
	}
}

func (pe *PolicyEngine) checkReload() {
	rulesChanged := false

	info, err := os.Stat(pe.RulesFile)
	if err != nil {
		if os.IsNotExist(err) {
			// File removed — clear rules and rate limit zones.
			pe.mu.Lock()
			if len(pe.rules) > 0 {
				pe.logger.Warn("rules file removed, clearing rules",
					zap.String("file", pe.RulesFile))
				pe.rules = nil
				pe.rlGlobalConfig = nil
				pe.lastMod = time.Time{}
			}
			pe.mu.Unlock()
			if pe.rlState != nil {
				pe.rlState.updateZones(nil)
			}
		}
		return
	}

	if info.ModTime().After(pe.lastMod) {
		rulesChanged = true
	}

	// Check default rules file for changes too.
	if pe.DefaultRulesFile != "" {
		dInfo, dErr := os.Stat(pe.DefaultRulesFile)
		if dErr == nil {
			if dInfo.ModTime().After(pe.lastDefaultMod) {
				rulesChanged = true
			}
		} else if os.IsNotExist(dErr) && !pe.lastDefaultMod.IsZero() {
			// Default file removed — trigger reload to clear defaults.
			rulesChanged = true
		}
	}

	if !rulesChanged {
		return
	}

	if err := pe.loadFromFile(); err != nil {
		pe.logger.Error("hot reload failed, keeping old rules",
			zap.String("file", pe.RulesFile), zap.Error(err))
	}
}

func (pe *PolicyEngine) loadFromFile() error {
	// Open and stat the same file descriptor to avoid TOCTOU races
	// (the file could be modified between a separate ReadFile and Stat).
	f, err := os.Open(pe.RulesFile)
	if err != nil {
		return fmt.Errorf("opening rules file: %w", err)
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return fmt.Errorf("stat rules file: %w", err)
	}

	data, err := io.ReadAll(f)
	if err != nil {
		return fmt.Errorf("reading rules file: %w", err)
	}

	var file PolicyRulesFile
	if err := json.Unmarshal(data, &file); err != nil {
		return fmt.Errorf("parsing rules file: %w", err)
	}

	// Load default rules if configured.
	var defaultRules []PolicyRule
	var defaultMod time.Time
	if pe.DefaultRulesFile != "" {
		var loadErr error
		defaultRules, defaultMod, loadErr = loadDefaultRulesFile(pe.DefaultRulesFile)
		if loadErr != nil {
			pe.logger.Warn("failed to load default rules file, continuing without defaults",
				zap.String("file", pe.DefaultRulesFile), zap.Error(loadErr))
		}
	}

	// Merge default rules with user rules.
	merged := mergeDefaultAndUserRules(defaultRules, file.Rules, file.DisabledDefaultRules)

	compiled, err := compileRules(merged)
	if err != nil {
		return fmt.Errorf("compiling rules: %w", err)
	}

	// Parse global rate limit config.
	globalCfg := compileRLGlobalConfig(file.RateLimitConfig)

	// Compile response headers (CSP + security) for O(1) per-request lookup.
	respHeaders := compileResponseHeaders(file.ResponseHeaders)

	// Compile WAF config (anomaly scoring thresholds + paranoia levels).
	wafCfg := compileWafConfig(file.WafConfig)

	// Check if sweep interval changed (need to restart sweep goroutine).
	oldSweepInterval := pe.sweepInterval()

	pe.mu.Lock()
	pe.rules = compiled
	pe.rlGlobalConfig = globalCfg
	pe.respHeaders = respHeaders
	pe.wafConfig = wafCfg
	pe.lastMod = info.ModTime()
	pe.lastDefaultMod = defaultMod
	pe.mu.Unlock()

	// Update rate limit zones — preserves counters for unchanged rules.
	if pe.rlState != nil {
		pe.rlState.updateZones(compiled)
	}

	// Restart sweep goroutine if the sweep interval changed.
	newSweepInterval := pe.sweepInterval()
	if newSweepInterval != oldSweepInterval {
		pe.logger.Info("sweep interval changed, restarting sweep goroutine",
			zap.Duration("old", oldSweepInterval),
			zap.Duration("new", newSweepInterval))
		pe.restartSweep()
	}

	enabledCount := 0
	rlCount := 0
	detectCount := 0
	defaultCount := len(defaultRules)
	disabledCount := len(file.DisabledDefaultRules)
	for _, r := range compiled {
		if r.rule.Enabled {
			enabledCount++
		}
		if r.rule.Type == "rate_limit" {
			rlCount++
		}
		if r.rule.Type == "detect" {
			detectCount++
		}
	}
	hasCSP := respHeaders != nil && respHeaders.csp != nil && respHeaders.csp.enabled
	hasSec := respHeaders != nil && respHeaders.security != nil && respHeaders.security.enabled
	pe.logger.Info("rules loaded",
		zap.Int("total", len(compiled)),
		zap.Int("enabled", enabledCount),
		zap.Int("default_rules", defaultCount),
		zap.Int("disabled_defaults", disabledCount),
		zap.Int("rate_limit_zones", rlCount),
		zap.Int("detect_rules", detectCount),
		zap.Bool("csp_enabled", hasCSP),
		zap.Bool("security_headers_enabled", hasSec),
		zap.String("generated", file.Generated))

	return nil
}

// ─── Caddyfile Parsing ──────────────────────────────────────────────

func (pe *PolicyEngine) UnmarshalCaddyfile(d *caddyfile.Dispenser) error {
	d.Next() // consume directive name

	for d.NextBlock(0) {
		switch d.Val() {
		case "rules_file":
			if !d.NextArg() {
				return d.ArgErr()
			}
			pe.RulesFile = d.Val()

		case "default_rules_file":
			if !d.NextArg() {
				return d.ArgErr()
			}
			pe.DefaultRulesFile = d.Val()

		case "reload_interval":
			if !d.NextArg() {
				return d.ArgErr()
			}
			dur, err := caddy.ParseDuration(d.Val())
			if err != nil {
				return d.Errf("invalid reload_interval: %v", err)
			}
			pe.ReloadInterval = caddy.Duration(dur)

		case "body_max_size":
			if !d.NextArg() {
				return d.ArgErr()
			}
			size, err := parseSize(d.Val())
			if err != nil {
				return d.Errf("invalid body_max_size: %v", err)
			}
			pe.BodyMaxSize = size

		case "hide_headers":
			pe.HideHeaders = true

		case "rule":
			rule, err := parseInlineRule(d)
			if err != nil {
				return err
			}
			pe.Rules = append(pe.Rules, rule)

		default:
			return d.Errf("unrecognized option: %s", d.Val())
		}
	}

	return nil
}

func parseInlineRule(d *caddyfile.Dispenser) (PolicyRule, error) {
	var rule PolicyRule
	rule.Enabled = true // inline rules default to enabled
	rule.GroupOp = "and"

	for nesting := d.Nesting(); d.NextBlock(nesting); {
		switch d.Val() {
		case "id":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.ID = d.Val()
		case "name":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Name = d.Val()
		case "type":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Type = d.Val()
		case "group_op":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.GroupOp = d.Val()
		case "priority":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			var p int
			if _, err := fmt.Sscanf(d.Val(), "%d", &p); err != nil {
				return rule, d.Errf("invalid priority: %v", err)
			}
			rule.Priority = p
		case "condition":
			args := d.RemainingArgs()
			if len(args) < 3 {
				return rule, d.Errf("condition requires: field operator value")
			}
			rule.Conditions = append(rule.Conditions, PolicyCondition{
				Field:    args[0],
				Operator: args[1],
				Value:    strings.Join(args[2:], " "),
			})
		default:
			return rule, d.Errf("unrecognized rule option: %s", d.Val())
		}
	}

	return rule, nil
}

// parseSize parses a human-readable size string like "13mb", "1024kb", "5gb".
// Supports kb, mb, gb suffixes (case-insensitive). Plain numbers are bytes.
func parseSize(s string) (int64, error) {
	s = strings.TrimSpace(strings.ToLower(s))
	multiplier := int64(1)
	switch {
	case strings.HasSuffix(s, "gb"):
		multiplier = 1024 * 1024 * 1024
		s = strings.TrimSuffix(s, "gb")
	case strings.HasSuffix(s, "mb"):
		multiplier = 1024 * 1024
		s = strings.TrimSuffix(s, "mb")
	case strings.HasSuffix(s, "kb"):
		multiplier = 1024
		s = strings.TrimSuffix(s, "kb")
	}
	n, err := strconv.ParseInt(strings.TrimSpace(s), 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid size %q: %w", s, err)
	}
	return n * multiplier, nil
}

func parseCaddyfilePolicyEngine(h httpcaddyfile.Helper) (caddyhttp.MiddlewareHandler, error) {
	pe := new(PolicyEngine)
	err := pe.UnmarshalCaddyfile(h.Dispenser)
	return pe, err
}

// ─── Interface Assertions ───────────────────────────────────────────

var (
	_ caddy.Module                = (*PolicyEngine)(nil)
	_ caddy.Provisioner           = (*PolicyEngine)(nil)
	_ caddy.Validator             = (*PolicyEngine)(nil)
	_ caddy.CleanerUpper          = (*PolicyEngine)(nil)
	_ caddyhttp.MiddlewareHandler = (*PolicyEngine)(nil)
	_ caddyfile.Unmarshaler       = (*PolicyEngine)(nil)
)
