// Package policyengine provides a Caddy HTTP middleware handler that evaluates
// allow/block/honeypot policy rules with correct matching semantics. It replaces
// Coraza SecRule generation for these rule types, fixing the @pm substring
// matching issue (e.g., @pm /admin matching /administrator).
//
// Rules are loaded from a JSON file generated by wafctl and hot-reloaded via
// mtime polling. The plugin sets Caddy variables for allow rules so downstream
// handlers (like coraza_waf) can be conditionally skipped.
//
// Module ID: http.handlers.policy_engine
package policyengine

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/caddyconfig/caddyfile"
	"github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	"go.uber.org/zap"
)

func init() {
	caddy.RegisterModule(PolicyEngine{})
	httpcaddyfile.RegisterHandlerDirective("policy_engine", parseCaddyfilePolicyEngine)
}

// ─── Types ──────────────────────────────────────────────────────────

// PolicyEngine evaluates allow/block/honeypot rules before the WAF.
type PolicyEngine struct {
	// RulesFile is the path to the JSON policy rules file generated by wafctl.
	RulesFile string `json:"rules_file,omitempty"`

	// Rules are inline policy rules (alternative to RulesFile for testing).
	Rules []PolicyRule `json:"rules,omitempty"`

	// ReloadInterval is how often to check RulesFile for changes. Default 5s.
	ReloadInterval caddy.Duration `json:"reload_interval,omitempty"`

	// compiled state (not serialized)
	rules    []compiledRule
	logger   *zap.Logger
	mu       *sync.RWMutex
	lastMod  time.Time
	stopPoll chan struct{}
}

// PolicyRulesFile is the top-level JSON structure of the rules file.
type PolicyRulesFile struct {
	Rules     []PolicyRule `json:"rules"`
	Generated string       `json:"generated"`
	Version   int          `json:"version"`
}

// PolicyRule is a single policy rule.
type PolicyRule struct {
	ID         string            `json:"id"`
	Name       string            `json:"name"`
	Type       string            `json:"type"` // "allow", "block", "honeypot"
	Conditions []PolicyCondition `json:"conditions"`
	GroupOp    string            `json:"group_op"` // "and" or "or"
	Enabled    bool              `json:"enabled"`
	Priority   int               `json:"priority"`
}

// PolicyCondition is a single match condition.
type PolicyCondition struct {
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    string `json:"value"`
	// Phase 2: managed list support
	ListItems []string `json:"list_items,omitempty"`
	ListKind  string   `json:"list_kind,omitempty"`
}

// ─── Compiled State ─────────────────────────────────────────────────

type compiledRule struct {
	rule       PolicyRule
	conditions []compiledCondition
}

type compiledCondition struct {
	field     string
	operator  string
	name      string // for named fields (header, cookie, args, etc.)
	exactVal  string
	prefix    string
	suffix    string
	contains  string
	regex     *regexp.Regexp
	ipNets    []net.IPNet
	stringSet map[string]bool
	negate    bool
}

// ─── Caddy Module Interface ─────────────────────────────────────────

func (PolicyEngine) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.policy_engine",
		New: func() caddy.Module { return new(PolicyEngine) },
	}
}

func (pe *PolicyEngine) Provision(ctx caddy.Context) error {
	pe.logger = ctx.Logger()
	pe.mu = &sync.RWMutex{}

	if pe.ReloadInterval == 0 {
		pe.ReloadInterval = caddy.Duration(5 * time.Second)
	}

	// Load rules from file or inline config.
	if pe.RulesFile != "" {
		if err := pe.loadFromFile(); err != nil {
			// Not fatal — file may not exist yet. Start with empty rules.
			pe.logger.Warn("failed to load rules file, starting empty",
				zap.String("file", pe.RulesFile), zap.Error(err))
			pe.rules = nil
		}
		// Start hot-reload polling.
		pe.stopPoll = make(chan struct{})
		go pe.pollForChanges()
	} else if len(pe.Rules) > 0 {
		compiled, err := compileRules(pe.Rules)
		if err != nil {
			return fmt.Errorf("compiling inline rules: %w", err)
		}
		pe.rules = compiled
	}

	ruleCount := len(pe.rules)
	enabledCount := 0
	for _, r := range pe.rules {
		if r.rule.Enabled {
			enabledCount++
		}
	}
	pe.logger.Info("policy engine provisioned",
		zap.Int("rules", ruleCount),
		zap.Int("enabled", enabledCount),
		zap.String("rules_file", pe.RulesFile))

	return nil
}

func (pe *PolicyEngine) Validate() error {
	if pe.RulesFile == "" && len(pe.Rules) == 0 {
		return fmt.Errorf("either rules_file or inline rules must be configured")
	}
	return nil
}

func (pe *PolicyEngine) Cleanup() error {
	if pe.stopPoll != nil {
		close(pe.stopPoll)
	}
	return nil
}

// ─── ServeHTTP ──────────────────────────────────────────────────────

func (pe *PolicyEngine) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyhttp.Handler) error {
	pe.mu.RLock()
	rules := pe.rules
	pe.mu.RUnlock()

	for _, cr := range rules {
		if !cr.rule.Enabled {
			continue
		}

		if !matchRule(cr, r) {
			continue
		}

		// Rule matched — take action.
		switch cr.rule.Type {
		case "allow":
			caddyhttp.SetVar(r.Context(), "policy_engine.action", "allow")
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_id", cr.rule.ID)
			caddyhttp.SetVar(r.Context(), "policy_engine.rule_name", cr.rule.Name)
			pe.logger.Info("policy allow",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return next.ServeHTTP(w, r)

		case "block", "honeypot":
			w.Header().Set("X-Blocked-By", "policy-engine")
			w.Header().Set("X-Blocked-Rule", cr.rule.Name)
			pe.logger.Info("policy block",
				zap.String("rule_id", cr.rule.ID),
				zap.String("rule_name", cr.rule.Name),
				zap.String("type", cr.rule.Type),
				zap.String("client_ip", clientIP(r)),
				zap.String("uri", r.RequestURI))
			return caddyhttp.Error(http.StatusForbidden, nil)
		}
	}

	// No rule matched — pass through.
	return next.ServeHTTP(w, r)
}

// ─── Rule Matching ──────────────────────────────────────────────────

func matchRule(cr compiledRule, r *http.Request) bool {
	if len(cr.conditions) == 0 {
		// No conditions = matches all requests.
		return true
	}

	if cr.rule.GroupOp == "or" {
		for _, cc := range cr.conditions {
			if matchCondition(cc, r) {
				return true
			}
		}
		return false
	}

	// Default: AND — all conditions must match.
	for _, cc := range cr.conditions {
		if !matchCondition(cc, r) {
			return false
		}
	}
	return true
}

func matchCondition(cc compiledCondition, r *http.Request) bool {
	target := extractField(cc, r)
	result := evalOperator(cc, target)
	if cc.negate {
		return !result
	}
	return result
}

// extractField gets the request value for a condition's field.
func extractField(cc compiledCondition, r *http.Request) string {
	switch cc.field {
	case "ip":
		return clientIP(r)
	case "path":
		return r.URL.RequestURI()
	case "uri_path":
		return r.URL.Path
	case "host":
		return r.Host
	case "method":
		return r.Method
	case "user_agent":
		return r.Header.Get("User-Agent")
	case "query":
		return r.URL.RawQuery
	case "country":
		return r.Header.Get("Cf-Ipcountry")
	case "referer":
		return r.Header.Get("Referer")
	case "http_version":
		return r.Proto
	case "header":
		if cc.name != "" {
			return r.Header.Get(cc.name)
		}
		return ""
	case "cookie":
		if cc.name != "" {
			if c, err := r.Cookie(cc.name); err == nil {
				return c.Value
			}
		}
		return ""
	case "args":
		if cc.name != "" {
			return r.URL.Query().Get(cc.name)
		}
		return ""
	default:
		return ""
	}
}

// evalOperator evaluates the operator against the extracted target value.
// The negate flag is handled by the caller (matchCondition).
func evalOperator(cc compiledCondition, target string) bool {
	switch cc.operator {
	case "eq":
		return target == cc.exactVal
	case "neq":
		// neq is handled via negate flag; eval as eq.
		return target == cc.exactVal
	case "contains":
		return strings.Contains(target, cc.contains)
	case "begins_with":
		return strings.HasPrefix(target, cc.prefix)
	case "ends_with":
		return strings.HasSuffix(target, cc.suffix)
	case "regex":
		if cc.regex != nil {
			return cc.regex.MatchString(target)
		}
		return false
	case "ip_match", "not_ip_match":
		ip := net.ParseIP(target)
		if ip == nil {
			return false
		}
		for _, n := range cc.ipNets {
			if n.Contains(ip) {
				return true
			}
		}
		return false
	case "in":
		return cc.stringSet[target]
	default:
		return false
	}
}

// clientIP extracts the client IP from the request, stripping the port.
func clientIP(r *http.Request) string {
	// Caddy sets r.RemoteAddr to the real client IP (after trusted_proxies resolution).
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}

// ─── Rule Compilation ───────────────────────────────────────────────

func compileRules(rules []PolicyRule) ([]compiledRule, error) {
	var compiled []compiledRule
	for _, rule := range rules {
		cr, err := compileRule(rule)
		if err != nil {
			return nil, fmt.Errorf("rule %q (%s): %w", rule.Name, rule.ID, err)
		}
		compiled = append(compiled, cr)
	}

	// Sort by priority (lower first), then by ID for determinism.
	sort.Slice(compiled, func(i, j int) bool {
		if compiled[i].rule.Priority != compiled[j].rule.Priority {
			return compiled[i].rule.Priority < compiled[j].rule.Priority
		}
		return compiled[i].rule.ID < compiled[j].rule.ID
	})

	return compiled, nil
}

func compileRule(rule PolicyRule) (compiledRule, error) {
	cr := compiledRule{rule: rule}

	for _, cond := range rule.Conditions {
		cc, err := compileCondition(cond)
		if err != nil {
			return cr, fmt.Errorf("condition %s %s: %w", cond.Field, cond.Operator, err)
		}
		cr.conditions = append(cr.conditions, cc)
	}

	return cr, nil
}

func compileCondition(cond PolicyCondition) (compiledCondition, error) {
	cc := compiledCondition{
		field:    cond.Field,
		operator: cond.Operator,
	}

	// Parse named fields: "Name:value" format.
	value := cond.Value
	switch cond.Field {
	case "header", "cookie", "args", "body_form", "response_header":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	case "body_json":
		if idx := strings.IndexByte(value, ':'); idx >= 0 {
			cc.name = value[:idx]
			value = value[idx+1:]
		}
	}

	// Handle negate operators.
	switch cond.Operator {
	case "neq", "not_ip_match":
		cc.negate = true
	}

	// Compile based on operator.
	switch cond.Operator {
	case "eq", "neq":
		cc.exactVal = value

	case "contains":
		cc.contains = value

	case "begins_with":
		cc.prefix = value

	case "ends_with":
		cc.suffix = value

	case "regex":
		re, err := regexp.Compile(value)
		if err != nil {
			return cc, fmt.Errorf("invalid regex %q: %w", value, err)
		}
		cc.regex = re

	case "ip_match", "not_ip_match":
		nets, err := parseIPNets(value)
		if err != nil {
			return cc, fmt.Errorf("invalid IP/CIDR %q: %w", value, err)
		}
		cc.ipNets = nets

	case "in":
		// Accept both pipe-separated ("a|b|c") and space-separated ("a b c") values.
		// The wafctl frontend stores "in" values with pipes (PipeTagInput convention),
		// while some seeded rules use spaces. Normalize pipes to spaces, then split.
		cc.stringSet = make(map[string]bool)
		normalized := strings.ReplaceAll(value, "|", " ")
		for _, item := range strings.Fields(normalized) {
			cc.stringSet[item] = true
		}

	default:
		return cc, fmt.Errorf("unsupported operator %q", cond.Operator)
	}

	return cc, nil
}

// parseIPNets parses a comma-or-space-separated list of IPs and CIDRs.
func parseIPNets(value string) ([]net.IPNet, error) {
	// Normalize: replace commas with spaces, then split.
	normalized := strings.ReplaceAll(value, ",", " ")
	tokens := strings.Fields(normalized)

	var nets []net.IPNet
	for _, tok := range tokens {
		if strings.Contains(tok, "/") {
			_, ipNet, err := net.ParseCIDR(tok)
			if err != nil {
				return nil, fmt.Errorf("parsing CIDR %q: %w", tok, err)
			}
			nets = append(nets, *ipNet)
		} else {
			ip := net.ParseIP(tok)
			if ip == nil {
				return nil, fmt.Errorf("parsing IP %q: invalid address", tok)
			}
			// Single IP → /32 or /128 mask.
			mask := net.CIDRMask(32, 32)
			if ip.To4() == nil {
				mask = net.CIDRMask(128, 128)
			}
			nets = append(nets, net.IPNet{IP: ip, Mask: mask})
		}
	}

	return nets, nil
}

// ─── Hot Reload ─────────────────────────────────────────────────────

func (pe *PolicyEngine) pollForChanges() {
	ticker := time.NewTicker(time.Duration(pe.ReloadInterval))
	defer ticker.Stop()

	for {
		select {
		case <-pe.stopPoll:
			return
		case <-ticker.C:
			pe.checkReload()
		}
	}
}

func (pe *PolicyEngine) checkReload() {
	info, err := os.Stat(pe.RulesFile)
	if err != nil {
		if os.IsNotExist(err) {
			// File removed — clear rules.
			pe.mu.Lock()
			if len(pe.rules) > 0 {
				pe.logger.Warn("rules file removed, clearing rules",
					zap.String("file", pe.RulesFile))
				pe.rules = nil
				pe.lastMod = time.Time{}
			}
			pe.mu.Unlock()
		}
		return
	}

	if !info.ModTime().After(pe.lastMod) {
		return
	}

	if err := pe.loadFromFile(); err != nil {
		pe.logger.Error("hot reload failed, keeping old rules",
			zap.String("file", pe.RulesFile), zap.Error(err))
	}
}

func (pe *PolicyEngine) loadFromFile() error {
	data, err := os.ReadFile(pe.RulesFile)
	if err != nil {
		return fmt.Errorf("reading rules file: %w", err)
	}

	var file PolicyRulesFile
	if err := json.Unmarshal(data, &file); err != nil {
		return fmt.Errorf("parsing rules file: %w", err)
	}

	compiled, err := compileRules(file.Rules)
	if err != nil {
		return fmt.Errorf("compiling rules: %w", err)
	}

	info, _ := os.Stat(pe.RulesFile)

	pe.mu.Lock()
	pe.rules = compiled
	if info != nil {
		pe.lastMod = info.ModTime()
	}
	pe.mu.Unlock()

	enabledCount := 0
	for _, r := range compiled {
		if r.rule.Enabled {
			enabledCount++
		}
	}
	pe.logger.Info("rules loaded",
		zap.Int("total", len(compiled)),
		zap.Int("enabled", enabledCount),
		zap.String("generated", file.Generated))

	return nil
}

// ─── Caddyfile Parsing ──────────────────────────────────────────────

func (pe *PolicyEngine) UnmarshalCaddyfile(d *caddyfile.Dispenser) error {
	d.Next() // consume directive name

	for d.NextBlock(0) {
		switch d.Val() {
		case "rules_file":
			if !d.NextArg() {
				return d.ArgErr()
			}
			pe.RulesFile = d.Val()

		case "reload_interval":
			if !d.NextArg() {
				return d.ArgErr()
			}
			dur, err := caddy.ParseDuration(d.Val())
			if err != nil {
				return d.Errf("invalid reload_interval: %v", err)
			}
			pe.ReloadInterval = caddy.Duration(dur)

		case "rule":
			rule, err := parseInlineRule(d)
			if err != nil {
				return err
			}
			pe.Rules = append(pe.Rules, rule)

		default:
			return d.Errf("unrecognized option: %s", d.Val())
		}
	}

	return nil
}

func parseInlineRule(d *caddyfile.Dispenser) (PolicyRule, error) {
	var rule PolicyRule
	rule.Enabled = true // inline rules default to enabled
	rule.GroupOp = "and"

	for nesting := d.Nesting(); d.NextBlock(nesting); {
		switch d.Val() {
		case "id":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.ID = d.Val()
		case "name":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Name = d.Val()
		case "type":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.Type = d.Val()
		case "group_op":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			rule.GroupOp = d.Val()
		case "priority":
			if !d.NextArg() {
				return rule, d.ArgErr()
			}
			var p int
			if _, err := fmt.Sscanf(d.Val(), "%d", &p); err != nil {
				return rule, d.Errf("invalid priority: %v", err)
			}
			rule.Priority = p
		case "condition":
			args := d.RemainingArgs()
			if len(args) < 3 {
				return rule, d.Errf("condition requires: field operator value")
			}
			rule.Conditions = append(rule.Conditions, PolicyCondition{
				Field:    args[0],
				Operator: args[1],
				Value:    strings.Join(args[2:], " "),
			})
		default:
			return rule, d.Errf("unrecognized rule option: %s", d.Val())
		}
	}

	return rule, nil
}

func parseCaddyfilePolicyEngine(h httpcaddyfile.Helper) (caddyhttp.MiddlewareHandler, error) {
	pe := new(PolicyEngine)
	err := pe.UnmarshalCaddyfile(h.Dispenser)
	return pe, err
}

// ─── Interface Assertions ───────────────────────────────────────────

var (
	_ caddy.Module                = (*PolicyEngine)(nil)
	_ caddy.Provisioner           = (*PolicyEngine)(nil)
	_ caddy.Validator             = (*PolicyEngine)(nil)
	_ caddy.CleanerUpper          = (*PolicyEngine)(nil)
	_ caddyhttp.MiddlewareHandler = (*PolicyEngine)(nil)
	_ caddyfile.Unmarshaler       = (*PolicyEngine)(nil)
)
